export const coreCustomerSlugs = ['camping', 'domki', 'cennik', 'dojazd', 'atrakcje', 'galeria', 'kontakt', 'faq', 'dla-kamperow', 'dla-rodzin', 'regulamin', 'polityka-prywatnosci'] as const;
export type CoreCustomerSlug = typeof coreCustomerSlugs[number];

type CorePage = {
  overline: string;
  title: string;
  lead: string;
  highlights: Array<[string, string]>;
};

type CoreLanguage = {
  info: string;
  booking: string;
  home: string;
  prices: string;
  maps: string;
  contact: string;
  gallery: string;
  pages: Partial<Record<CoreCustomerSlug, CorePage>>;
};

export const corePages: Record<string, CoreLanguage> = {
  fr: {
    info: 'Informations essentielles', booking: 'Envoyer une demande', home: 'Accueil', prices: 'Voir les tarifs', maps: 'Ouvrir Google Maps', contact: 'Contacter la réception', gallery: 'Photos du camping',
    pages: {
      camping: { overline: 'Camping à Cracovie', title: 'Emplacements pour camping-cars, caravanes, vans et tentes', lead: 'Une base verdoyante en ville, près du tramway et du centre de Cracovie.', highlights: [['Juillet et août', 'Les emplacements de camping sont attribués par ordre d’arrivée. Les réservations à l’avance concernent uniquement les bungalows.'], ['Électricité 10A', 'Branchement 10A disponible. Il ne sert pas à recharger les véhicules électriques.'], ['Camping urbain et calme', 'Calme de 22h00 à 07h00. On peut parfois entendre les tramways, les avions et la vie normale de la ville.']] },
      domki: { overline: 'Bungalows', title: 'Bungalows pour 2, 3 et 4 personnes', lead: 'Un hébergement simple et pratique à Cracovie, sans votre propre équipement de camping.', highlights: [['Horaires', 'Arrivée à partir de 16h00, départ avant 11h00.'], ['À apporter', 'Prévoyez vos serviettes, produits de toilette et effets personnels.'], ['Disponibilité', 'La réception confirme toujours les dates, le prix final et les conditions.']] },
      cennik: { overline: 'Tarifs', title: 'Tarifs Camping Clepardia', lead: 'Consultez les prix indicatifs et envoyez une demande pour vos dates.', highlights: [['Camping', 'Le prix dépend du nombre de personnes, du véhicule, de l’emplacement et des services choisis.'], ['Bungalows', 'Tarifs saisonniers pour les bungalows de 2, 3 et 4 personnes.'], ['Prix indicatif', 'Le calculateur donne une estimation. La réception confirme le montant final.']] },
      dojazd: { overline: 'Accès', title: 'Comment venir au Camping Clepardia', lead: 'Utilisez Google Maps : l’accès a changé en 2022 et les anciens GPS peuvent se tromper.', highlights: [['Adresse', 'Henryka Pachońskiego 28A, 31-322 Cracovie.'], ['Tramway', 'L’arrêt Górnickiego est à environ 40 m. La ligne 18 rejoint Stary Kleparz en environ 14 minutes.'], ['Véhicules lourds', 'Signalez les véhicules lourds ou longs dans la demande afin que la réception puisse préparer une surface adaptée.']] },
      atrakcje: { overline: 'Cracovie et environs', title: 'Attractions depuis le Camping Clepardia', lead: 'Visitez facilement le centre de Cracovie et planifiez une excursion dans la région.', highlights: [['Cracovie', 'Vieille Ville, Wawel, Kazimierz et musées accessibles en tramway.'], ['Excursions', 'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców et Energylandia.'], ['Sans déplacer le véhicule', 'Laissez votre voiture ou camping-car sur place et rejoignez le centre en tramway.']] },
      galeria: { overline: 'Galerie', title: 'Découvrez Camping Clepardia', lead: 'Emplacements, bungalows, sanitaires, espaces verts et réception.', highlights: [['Camping', 'Emplacements et espaces verts pour différents types de véhicules et de tentes.'], ['Bungalows', 'Bungalows et intérieurs pour 2, 3 ou 4 personnes.'], ['Installations', 'Réception, cuisine touristique, sanitaires et espaces communs.']] },
      kontakt: { overline: 'Contact', title: 'Contacter Camping Clepardia', lead: 'Téléphone, e-mail, adresse et accès rapide au formulaire de séjour.', highlights: [['Téléphone', '+48 795 294 486'], ['E-mail', 'clepardia@gmail.com'], ['Réception', 'Ouverte habituellement de 9h00 à 21h00. Pour une arrivée tardive, contactez-nous à l’avance.']] },
      faq: { overline: 'Questions fréquentes', title: 'Informations utiles avant l’arrivée', lead: 'Réponses rapides sur les réservations, les horaires, les animaux, l’électricité et l’accès.', highlights: [['Puis-je réserver un emplacement en été ?', 'En juillet et août, les emplacements sont disponibles par ordre d’arrivée. Les bungalows peuvent être réservés.'], ['Les chiens sont-ils acceptés ?', 'Oui. Le tarif pour un chien est de 0 PLN ; merci de ramasser après votre animal.'], ['Quels documents apporter ?', 'Une pièce d’identité et le numéro d’immatriculation du véhicule et, le cas échéant, de la caravane.']] },
    },
  },
  es: {
    info: 'Información esencial', booking: 'Enviar una consulta', home: 'Inicio', prices: 'Ver precios', maps: 'Abrir Google Maps', contact: 'Contactar con recepción', gallery: 'Fotos del camping',
    pages: {
      camping: { overline: 'Camping en Cracovia', title: 'Parcelas para autocaravanas, caravanas, furgonetas y tiendas', lead: 'Una base verde dentro de la ciudad, cerca del tranvía y del centro de Cracovia.', highlights: [['Julio y agosto', 'Las parcelas se asignan por orden de llegada. Las reservas anticipadas son solo para bungalows.'], ['Electricidad 10A', 'Hay conexión de 10A. No se utiliza para cargar vehículos eléctricos.'], ['Camping urbano y tranquilo', 'Silencio de 22:00 a 07:00. A veces se oyen tranvías, aviones y la vida normal de la ciudad.']] },
      domki: { overline: 'Bungalows', title: 'Bungalows para 2, 3 y 4 personas', lead: 'Alojamiento sencillo y práctico en Cracovia sin equipo propio de camping.', highlights: [['Horarios', 'Entrada desde las 16:00 y salida antes de las 11:00.'], ['Qué traer', 'Trae toallas, productos de aseo y objetos personales.'], ['Disponibilidad', 'Recepción confirma siempre las fechas, el precio final y las condiciones.']] },
      cennik: { overline: 'Precios', title: 'Precios de Camping Clepardia', lead: 'Consulta precios orientativos y envía una consulta para tus fechas.', highlights: [['Camping', 'El precio depende de personas, vehículo, parcela y servicios elegidos.'], ['Bungalows', 'Precios de temporada para bungalows de 2, 3 y 4 personas.'], ['Estimación', 'La calculadora ofrece un importe orientativo; recepción confirma el total final.']] },
      dojazd: { overline: 'Cómo llegar', title: 'Cómo llegar a Camping Clepardia', lead: 'Usa Google Maps: el acceso cambió en 2022 y los GPS antiguos pueden indicar mal.', highlights: [['Dirección', 'Henryka Pachońskiego 28A, 31-322 Cracovia.'], ['Tranvía', 'La parada Górnickiego está a unos 40 m. La línea 18 llega a Stary Kleparz en unos 14 minutos.'], ['Vehículos pesados', 'Indica vehículos largos o pesados en la consulta para preparar una superficie adecuada.']] },
      atrakcje: { overline: 'Cracovia y alrededores', title: 'Atracciones desde Camping Clepardia', lead: 'Visita fácilmente el centro de Cracovia y organiza excursiones por la región.', highlights: [['Cracovia', 'Casco antiguo, Wawel, Kazimierz y museos accesibles en tranvía.'], ['Excursiones', 'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców y Energylandia.'], ['Sin mover el vehículo', 'Deja el coche o la autocaravana en el camping y ve al centro en tranvía.']] },
      galeria: { overline: 'Galería', title: 'Conoce Camping Clepardia', lead: 'Parcelas, bungalows, sanitarios, zonas verdes y recepción.', highlights: [['Camping', 'Parcelas y espacios verdes para distintos vehículos y tiendas.'], ['Bungalows', 'Bungalows e interiores para 2, 3 y 4 personas.'], ['Instalaciones', 'Recepción, cocina turística, sanitarios y zonas comunes.']] },
      kontakt: { overline: 'Contacto', title: 'Contacta con Camping Clepardia', lead: 'Teléfono, email, dirección y acceso rápido al formulario de estancia.', highlights: [['Teléfono', '+48 795 294 486'], ['Email', 'clepardia@gmail.com'], ['Recepción', 'Normalmente abierta de 9:00 a 21:00. Para llegadas tardías, contacta antes.']] },
      faq: { overline: 'Preguntas frecuentes', title: 'Información útil antes de llegar', lead: 'Respuestas rápidas sobre reservas, horarios, mascotas, electricidad y acceso.', highlights: [['¿Puedo reservar una parcela en verano?', 'En julio y agosto las parcelas se asignan por orden de llegada. Los bungalows sí se pueden reservar.'], ['¿Se admiten perros?', 'Sí. El precio por perro es 0 PLN; recoge siempre sus excrementos.'], ['¿Qué documentos necesito?', 'Documento de identidad y matrícula del vehículo y, si corresponde, de la caravana.']] },
    },
  },
  nl: {
    info: 'Belangrijkste informatie', booking: 'Stuur een aanvraag', home: 'Start', prices: 'Bekijk prijzen', maps: 'Open Google Maps', contact: 'Neem contact op', gallery: 'Foto’s van de camping',
    pages: {
      camping: { overline: 'Camping in Krakau', title: 'Plaatsen voor campers, caravans, vans en tenten', lead: 'Een groene uitvalsbasis in de stad, dicht bij tram en centrum.', highlights: [['Juli en augustus', 'Kampeerplaatsen zijn beschikbaar op volgorde van aankomst. Vooraf reserveren kan alleen voor bungalows.'], ['10A stroom', 'Een 10A-aansluiting is beschikbaar. Deze is niet bedoeld voor het laden van elektrische voertuigen.'], ['Rustige stadscamping', 'Nachtrust van 22.00 tot 07.00 uur. Soms hoor je tram, vliegtuigen en het normale stadsleven.']] },
      domki: { overline: 'Bungalows', title: 'Bungalows voor 2, 3 en 4 personen', lead: 'Eenvoudig en praktisch overnachten in Krakau zonder eigen kampeeruitrusting.', highlights: [['Tijden', 'Inchecken vanaf 16.00 uur, uitchecken vóór 11.00 uur.'], ['Meenemen', 'Neem handdoeken, toiletartikelen en persoonlijke spullen mee.'], ['Beschikbaarheid', 'De receptie bevestigt altijd data, definitieve prijs en voorwaarden.']] },
      cennik: { overline: 'Prijzen', title: 'Prijzen Camping Clepardia', lead: 'Bekijk indicatieve prijzen en stuur een aanvraag voor je data.', highlights: [['Camping', 'De prijs hangt af van personen, voertuig, plaats en gekozen diensten.'], ['Bungalows', 'Seizoensprijzen voor bungalows voor 2, 3 en 4 personen.'], ['Indicatieve prijs', 'De calculator geeft een schatting; de receptie bevestigt het definitieve bedrag.']] },
      dojazd: { overline: 'Route', title: 'Route naar Camping Clepardia', lead: 'Gebruik Google Maps: de toegang veranderde in 2022 en oudere navigatie kan verkeerd sturen.', highlights: [['Adres', 'Henryka Pachońskiego 28A, 31-322 Krakau.'], ['Tram', 'Halte Górnickiego ligt op circa 40 m. Lijn 18 bereikt Stary Kleparz in ongeveer 14 minuten.'], ['Zware voertuigen', 'Vermeld lange of zware voertuigen in de aanvraag zodat de receptie een geschikte ondergrond kan voorbereiden.']] },
      atrakcje: { overline: 'Krakau en omgeving', title: 'Bezienswaardigheden vanaf Camping Clepardia', lead: 'Bezoek eenvoudig het centrum en plan een uitstapje in de regio.', highlights: [['Krakau', 'Oude Stad, Wawel, Kazimierz en musea zijn bereikbaar met de tram.'], ['Uitstapjes', 'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców en Energylandia.'], ['Laat het voertuig staan', 'Laat auto of camper op de camping en ga met de tram naar het centrum.']] },
      galeria: { overline: 'Galerij', title: 'Bekijk Camping Clepardia', lead: 'Plaatsen, bungalows, sanitair, groen en receptie.', highlights: [['Camping', 'Plaatsen en groen voor verschillende voertuigen en tenten.'], ['Bungalows', 'Bungalows en interieurs voor 2, 3 en 4 personen.'], ['Voorzieningen', 'Receptie, gastenkeuken, sanitair en gemeenschappelijke ruimtes.']] },
      kontakt: { overline: 'Contact', title: 'Contact met Camping Clepardia', lead: 'Telefoon, e-mail, adres en snelle toegang tot de verblijfsaanvraag.', highlights: [['Telefoon', '+48 795 294 486'], ['E-mail', 'clepardia@gmail.com'], ['Receptie', 'Gewoonlijk open van 9.00 tot 21.00 uur. Neem bij late aankomst vooraf contact op.']] },
      faq: { overline: 'Veelgestelde vragen', title: 'Handige informatie vóór aankomst', lead: 'Snelle antwoorden over reserveren, tijden, huisdieren, stroom en route.', highlights: [['Kan ik in de zomer reserveren?', 'In juli en augustus zijn kampeerplaatsen op volgorde van aankomst. Bungalows kunnen wel worden gereserveerd.'], ['Zijn honden toegestaan?', 'Ja. Een hond kost 0 PLN; ruim altijd op na je huisdier.'], ['Welke documenten heb ik nodig?', 'Identiteitsbewijs en kenteken van voertuig en, indien van toepassing, caravan.']] },
    },
  },
  cs: {
    info: 'Nejdůležitější informace', booking: 'Odeslat dotaz', home: 'Úvod', prices: 'Zobrazit ceny', maps: 'Otevřít Google Maps', contact: 'Kontaktovat recepci', gallery: 'Fotografie kempu',
    pages: {
      camping: { overline: 'Kemp v Krakově', title: 'Místa pro obytné vozy, karavany, dodávky a stany', lead: 'Zelená městská základna blízko tramvaje a centra Krakova.', highlights: [['Červenec a srpen', 'Místa v kempu jsou dostupná podle pořadí příjezdu. Rezervace předem platí jen pro bungalovy.'], ['Elektřina 10A', 'K dispozici je přípojka 10A. Není určena k nabíjení elektromobilů.'], ['Klidný městský kemp', 'Noční klid 22:00–07:00. Někdy je slyšet tramvaje, letadla a běžný život města.']] },
      domki: { overline: 'Bungalovy', title: 'Bungalovy pro 2, 3 a 4 osoby', lead: 'Jednoduché a praktické ubytování v Krakově bez vlastního vybavení.', highlights: [['Časy', 'Příjezd od 16:00, odjezd do 11:00.'], ['Co si vzít', 'Vezměte si ručníky, hygienické potřeby a osobní věci.'], ['Dostupnost', 'Recepce vždy potvrdí termín, konečnou cenu a podmínky.']] },
      cennik: { overline: 'Ceny', title: 'Ceník Camping Clepardia', lead: 'Zkontrolujte orientační ceny a odešlete dotaz na svůj termín.', highlights: [['Camping', 'Cena závisí na počtu osob, vozidle, místě a vybraných službách.'], ['Bungalovy', 'Sezónní ceny bungalovů pro 2, 3 a 4 osoby.'], ['Orientační cena', 'Kalkulačka ukazuje odhad; konečnou částku potvrdí recepce.']] },
      dojazd: { overline: 'Doprava', title: 'Jak se dostat do Camping Clepardia', lead: 'Použijte Google Maps: vjezd se v roce 2022 změnil a starší navigace může vést špatně.', highlights: [['Adresa', 'Henryka Pachońskiego 28A, 31-322 Krakov.'], ['Tramvaj', 'Zastávka Górnickiego je asi 40 m. Linka 18 jede na Stary Kleparz přibližně 14 minut.'], ['Těžká vozidla', 'Dlouhé nebo těžké vozidlo uveďte v dotazu, aby recepce připravila vhodný povrch.']] },
      atrakcje: { overline: 'Krakov a okolí', title: 'Atrakce z Camping Clepardia', lead: 'Snadno navštivte centrum Krakova a naplánujte výlet po regionu.', highlights: [['Krakov', 'Staré Město, Wawel, Kazimierz a muzea jsou dostupné tramvají.'], ['Výlety', 'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców a Energylandia.'], ['Bez přesunu vozidla', 'Auto nebo obytný vůz nechte v kempu a do centra jeďte tramvají.']] },
      galeria: { overline: 'Galerie', title: 'Prohlédněte si Camping Clepardia', lead: 'Místa, bungalovy, sociální zařízení, zeleň a recepce.', highlights: [['Camping', 'Místa a zelené plochy pro různá vozidla a stany.'], ['Bungalovy', 'Bungalovy a interiéry pro 2, 3 a 4 osoby.'], ['Zázemí', 'Recepce, kuchyňka pro hosty, sociální zařízení a společné prostory.']] },
      kontakt: { overline: 'Kontakt', title: 'Kontaktujte Camping Clepardia', lead: 'Telefon, e-mail, adresa a rychlý přístup k formuláři pobytu.', highlights: [['Telefon', '+48 795 294 486'], ['E-mail', 'clepardia@gmail.com'], ['Recepce', 'Obvykle otevřeno 9:00–21:00. Při pozdním příjezdu nás kontaktujte předem.']] },
      faq: { overline: 'Časté otázky', title: 'Užitečné informace před příjezdem', lead: 'Rychlé odpovědi o rezervaci, časech, zvířatech, elektřině a dopravě.', highlights: [['Lze v létě rezervovat místo?', 'V červenci a srpnu jsou místa podle pořadí příjezdu. Bungalovy rezervovat lze.'], ['Jsou psi povoleni?', 'Ano. Cena za psa je 0 PLN; vždy po něm ukliďte.'], ['Jaké doklady potřebuji?', 'Doklad totožnosti a registrační značku vozidla a případně karavanu.']] },
    },
  },
  sk: {
    info: 'Najdôležitejšie informácie', booking: 'Odoslať dopyt', home: 'Úvod', prices: 'Zobraziť ceny', maps: 'Otvoriť Google Maps', contact: 'Kontaktovať recepciu', gallery: 'Fotografie kempu',
    pages: {
      camping: { overline: 'Kemp v Krakove', title: 'Miesta pre obytné autá, karavany, dodávky a stany', lead: 'Zelená mestská základňa blízko električky a centra Krakova.', highlights: [['Júl a august', 'Miesta v kempe sú dostupné podľa poradia príchodu. Rezervácie vopred platia iba pre bungalovy.'], ['Elektrina 10A', 'K dispozícii je prípojka 10A. Nie je určená na nabíjanie elektromobilov.'], ['Pokojný mestský kemp', 'Nočný pokoj 22:00–07:00. Niekedy je počuť električky, lietadlá a bežný život mesta.']] },
      domki: { overline: 'Bungalovy', title: 'Bungalovy pre 2, 3 a 4 osoby', lead: 'Jednoduché a praktické ubytovanie v Krakove bez vlastného vybavenia.', highlights: [['Časy', 'Príchod od 16:00, odchod do 11:00.'], ['Čo si vziať', 'Prineste si uteráky, hygienické potreby a osobné veci.'], ['Dostupnosť', 'Recepcia vždy potvrdí termín, konečnú cenu a podmienky.']] },
      cennik: { overline: 'Ceny', title: 'Cenník Camping Clepardia', lead: 'Skontrolujte orientačné ceny a odošlite dopyt na svoj termín.', highlights: [['Camping', 'Cena závisí od počtu osôb, vozidla, miesta a vybraných služieb.'], ['Bungalovy', 'Sezónne ceny bungalovov pre 2, 3 a 4 osoby.'], ['Orientačná cena', 'Kalkulačka ukazuje odhad; konečnú sumu potvrdí recepcia.']] },
      dojazd: { overline: 'Doprava', title: 'Ako sa dostať do Camping Clepardia', lead: 'Použite Google Maps: vjazd sa v roku 2022 zmenil a staršia navigácia môže viesť zle.', highlights: [['Adresa', 'Henryka Pachońskiego 28A, 31-322 Krakov.'], ['Električka', 'Zastávka Górnickiego je asi 40 m. Linka 18 ide na Stary Kleparz približne 14 minút.'], ['Ťažké vozidlá', 'Dlhé alebo ťažké vozidlo uveďte v dopyte, aby recepcia pripravila vhodný povrch.']] },
      atrakcje: { overline: 'Krakov a okolie', title: 'Atrakcie z Camping Clepardia', lead: 'Jednoducho navštívte centrum Krakova a naplánujte výlet po regióne.', highlights: [['Krakov', 'Staré Mesto, Wawel, Kazimierz a múzeá sú dostupné električkou.'], ['Výlety', 'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców a Energylandia.'], ['Bez presunu vozidla', 'Auto alebo obytné vozidlo nechajte v kempe a do centra choďte električkou.']] },
      galeria: { overline: 'Galéria', title: 'Pozrite si Camping Clepardia', lead: 'Miesta, bungalovy, sociálne zariadenia, zeleň a recepcia.', highlights: [['Camping', 'Miesta a zelené plochy pre rôzne vozidlá a stany.'], ['Bungalovy', 'Bungalovy a interiéry pre 2, 3 a 4 osoby.'], ['Zázemie', 'Recepcia, kuchynka pre hostí, sociálne zariadenia a spoločné priestory.']] },
      kontakt: { overline: 'Kontakt', title: 'Kontaktujte Camping Clepardia', lead: 'Telefón, e-mail, adresa a rýchly prístup k formuláru pobytu.', highlights: [['Telefón', '+48 795 294 486'], ['E-mail', 'clepardia@gmail.com'], ['Recepcia', 'Zvyčajne otvorené 9:00–21:00. Pri neskorom príchode nás kontaktujte vopred.']] },
      faq: { overline: 'Časté otázky', title: 'Užitočné informácie pred príchodom', lead: 'Rýchle odpovede o rezervácii, časoch, zvieratách, elektrine a doprave.', highlights: [['Dá sa v lete rezervovať miesto?', 'V júli a auguste sú miesta podľa poradia príchodu. Bungalovy sa rezervovať dajú.'], ['Sú psy povolené?', 'Áno. Cena za psa je 0 PLN; vždy po ňom upracte.'], ['Aké doklady potrebujem?', 'Doklad totožnosti a evidenčné číslo vozidla a prípadne karavanu.']] },
    },
  },
  sv: {
    info: 'Viktig information', booking: 'Skicka en förfrågan', home: 'Start', prices: 'Se priser', maps: 'Öppna Google Maps', contact: 'Kontakta receptionen', gallery: 'Bilder från campingen',
    pages: {
      camping: { overline: 'Camping i Kraków', title: 'Platser för husbilar, husvagnar, vans och tält', lead: 'En grön bas i staden, nära spårvagn och centrum.', highlights: [['Juli och augusti', 'Campingplatser erbjuds i ankomstordning. Förhandsbokning gäller endast bungalower.'], ['10A el', '10A-anslutning finns. Den är inte avsedd för laddning av elfordon.'], ['Lugn stadscamping', 'Nattro 22.00–07.00. Ibland hörs spårvagnar, flygplan och vanligt stadsliv.']] },
      domki: { overline: 'Bungalower', title: 'Bungalower för 2, 3 och 4 personer', lead: 'Enkelt och praktiskt boende i Kraków utan egen campingutrustning.', highlights: [['Tider', 'Incheckning från 16.00, utcheckning senast 11.00.'], ['Ta med', 'Ta med handdukar, hygienartiklar och personliga saker.'], ['Tillgänglighet', 'Receptionen bekräftar alltid datum, slutpris och villkor.']] },
      cennik: { overline: 'Priser', title: 'Priser Camping Clepardia', lead: 'Se ungefärliga priser och skicka en förfrågan för dina datum.', highlights: [['Camping', 'Priset beror på antal personer, fordon, plats och valda tjänster.'], ['Bungalower', 'Säsongspriser för bungalower för 2, 3 och 4 personer.'], ['Ungefärligt pris', 'Kalkylatorn ger en uppskattning; receptionen bekräftar slutbeloppet.']] },
      dojazd: { overline: 'Vägbeskrivning', title: 'Hitta till Camping Clepardia', lead: 'Använd Google Maps: infarten ändrades 2022 och äldre navigation kan visa fel.', highlights: [['Adress', 'Henryka Pachońskiego 28A, 31-322 Kraków.'], ['Spårvagn', 'Hållplatsen Górnickiego ligger cirka 40 m bort. Linje 18 når Stary Kleparz på cirka 14 minuter.'], ['Tunga fordon', 'Ange långa eller tunga fordon i förfrågan så att receptionen kan förbereda lämpligt underlag.']] },
      atrakcje: { overline: 'Kraków med omnejd', title: 'Sevärdheter från Camping Clepardia', lead: 'Besök enkelt centrala Kraków och planera utflykter i regionen.', highlights: [['Kraków', 'Gamla stan, Wawel, Kazimierz och museer nås med spårvagn.'], ['Utflykter', 'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców och Energylandia.'], ['Låt fordonet stå', 'Lämna bil eller husbil på campingen och åk spårvagn till centrum.']] },
      galeria: { overline: 'Galleri', title: 'Se Camping Clepardia', lead: 'Platser, bungalower, servicebyggnader, grönska och reception.', highlights: [['Camping', 'Platser och gröna ytor för olika fordon och tält.'], ['Bungalower', 'Bungalower och interiörer för 2, 3 och 4 personer.'], ['Faciliteter', 'Reception, gästkök, sanitetsutrymmen och gemensamma ytor.']] },
      kontakt: { overline: 'Kontakt', title: 'Kontakta Camping Clepardia', lead: 'Telefon, e-post, adress och snabb väg till vistelseförfrågan.', highlights: [['Telefon', '+48 795 294 486'], ['E-post', 'clepardia@gmail.com'], ['Reception', 'Vanligtvis öppen 9.00–21.00. Kontakta oss i förväg vid sen ankomst.']] },
      faq: { overline: 'Vanliga frågor', title: 'Bra information före ankomst', lead: 'Snabba svar om bokning, tider, husdjur, el och vägbeskrivning.', highlights: [['Kan jag boka en campingplats på sommaren?', 'I juli och augusti erbjuds platser i ankomstordning. Bungalower kan bokas.'], ['Är hundar tillåtna?', 'Ja. Hund kostar 0 PLN; plocka alltid upp efter ditt djur.'], ['Vilka dokument behövs?', 'Identitetshandling och registreringsnummer för fordon och vid behov husvagn.']] },
    },
  },
};

Object.assign(corePages.fr.pages, {
  'dla-kamperow': { overline: 'Pour camping-cars', title: 'Informations pour camping-cars et caravanes', lead: 'Préparez un séjour simple : accès, électricité, documents et règles de calme.', highlights: [['Avant l’arrivée', 'Utilisez Google Maps, car l’accès a changé en 2022. Préparez votre pièce d’identité et l’immatriculation du véhicule.'], ['Sur place', 'Électricité 10A disponible, non destinée à la recharge des véhicules électriques. Les véhicules lourds sont dirigés vers une surface adaptée.'], ['Séjour', 'En juillet et août, les emplacements de camping sont attribués par ordre d’arrivée. Départ camping avant 12h00.']] },
  'dla-rodzin': { overline: 'Familles', title: 'Séjour familial à Camping Clepardia', lead: 'Une base verte en ville pour visiter Cracovie en tramway et revenir au calme.', highlights: [['Rythme', 'La ligne de tram est proche, vous pouvez visiter le centre sans déplacer la voiture.'], ['Règles', 'Calme de 22h00 à 07h00. Le camping n’est pas un lieu de fête.'], ['Bungalows', 'Arrivée à partir de 16h00. Apportez serviettes, produits de toilette et effets personnels.']] },
  regulamin: { overline: 'Règles', title: 'Règlement de séjour', lead: 'Les règles les plus importantes avant votre arrivée à Camping Clepardia.', highlights: [['Calme', 'Calme de 22h00 à 07h00 ; respectez les autres clients.'], ['Documents', 'La réception peut demander une pièce d’identité et les immatriculations du véhicule ou de la caravane.'], ['Animaux', 'Les chiens sont acceptés à 0 PLN ; merci de nettoyer après votre animal.']] },
  'polityka-prywatnosci': { overline: 'Confidentialité', title: 'Politique de confidentialité', lead: 'Données utilisées uniquement pour traiter les demandes de séjour et le contact avec la réception.', highlights: [['Contact', 'Nous utilisons les coordonnées pour répondre à votre demande.'], ['Réservation', 'Les informations de séjour aident la réception à vérifier la disponibilité.'], ['Sécurité', 'Les données techniques de diagnostic ne sont pas affichées dans l’interface publique.']] },
});

Object.assign(corePages.es.pages, {
  'dla-kamperow': { overline: 'Para autocaravanas', title: 'Información para autocaravanas y caravanas', lead: 'Prepara una estancia sencilla: acceso, electricidad, documentos y normas de silencio.', highlights: [['Antes de llegar', 'Usa Google Maps porque el acceso cambió en 2022. Prepara documento de identidad y matrícula.'], ['En el camping', 'Electricidad 10A disponible, no para cargar vehículos eléctricos. Los vehículos pesados se dirigen a una superficie adecuada.'], ['Estancia', 'En julio y agosto las parcelas se asignan por orden de llegada. Salida del camping antes de las 12:00.']] },
  'dla-rodzin': { overline: 'Familias', title: 'Estancia familiar en Camping Clepardia', lead: 'Una base verde en la ciudad para visitar Cracovia en tranvía y volver a un lugar tranquilo.', highlights: [['Ritmo', 'La parada de tranvía está cerca y permite visitar el centro sin mover el coche.'], ['Normas', 'Silencio de 22:00 a 07:00. No es un camping de fiestas.'], ['Bungalows', 'Entrada desde las 16:00. Trae toallas, productos de aseo y objetos personales.']] },
  regulamin: { overline: 'Normas', title: 'Normas de estancia', lead: 'Las reglas más importantes antes de llegar a Camping Clepardia.', highlights: [['Silencio', 'Silencio de 22:00 a 07:00; respeta a otros huéspedes.'], ['Documentos', 'Recepción puede pedir documento de identidad y matrículas del vehículo o caravana.'], ['Mascotas', 'Los perros son aceptados a 0 PLN; recoge siempre sus excrementos.']] },
  'polityka-prywatnosci': { overline: 'Privacidad', title: 'Política de privacidad', lead: 'Los datos se usan para gestionar consultas de estancia y el contacto con recepción.', highlights: [['Contacto', 'Usamos los datos de contacto para responder a la consulta.'], ['Reserva', 'Los datos de estancia ayudan a verificar disponibilidad.'], ['Seguridad', 'Los diagnósticos técnicos no se muestran en la interfaz pública.']] },
});

Object.assign(corePages.nl.pages, {
  'dla-kamperow': { overline: 'Voor campers', title: 'Informatie voor campers en caravans', lead: 'Bereid je verblijf voor: route, stroom, documenten en rustige campingregels.', highlights: [['Voor aankomst', 'Gebruik Google Maps, want de toegang veranderde in 2022. Neem ID en kenteken mee.'], ['Op locatie', '10A stroom beschikbaar, niet voor het laden van elektrische voertuigen. Zware voertuigen gaan naar een geschikte ondergrond.'], ['Verblijf', 'In juli en augustus zijn kampeerplaatsen op volgorde van aankomst. Check-out camping vóór 12.00 uur.']] },
  'dla-rodzin': { overline: 'Gezinnen', title: 'Familieverblijf op Camping Clepardia', lead: 'Een groene stadsbasis om Krakau per tram te bezoeken en rustig terug te komen.', highlights: [['Tempo', 'De tramhalte is dichtbij; bezoek het centrum zonder de auto te verplaatsen.'], ['Regels', 'Nachtrust 22.00–07.00 uur. Dit is geen feestcamping.'], ['Bungalows', 'Inchecken vanaf 16.00 uur. Neem handdoeken, toiletartikelen en persoonlijke spullen mee.']] },
  regulamin: { overline: 'Regels', title: 'Verblijfsregels', lead: 'De belangrijkste regels vóór aankomst bij Camping Clepardia.', highlights: [['Rust', 'Nachtrust 22.00–07.00 uur; respecteer andere gasten.'], ['Documenten', 'De receptie kan ID en kentekens van voertuig of caravan vragen.'], ['Dieren', 'Honden zijn welkom voor 0 PLN; ruim altijd op na je hond.']] },
  'polityka-prywatnosci': { overline: 'Privacy', title: 'Privacybeleid', lead: 'Gegevens worden gebruikt voor verblijfsaanvragen en contact met de receptie.', highlights: [['Contact', 'Contactgegevens gebruiken we om te antwoorden.'], ['Boeking', 'Verblijfsgegevens helpen beschikbaarheid te controleren.'], ['Veiligheid', 'Technische diagnostiek wordt niet getoond in de openbare UI.']] },
});

Object.assign(corePages.cs.pages, {
  'dla-kamperow': { overline: 'Pro obytné vozy', title: 'Informace pro obytné vozy a karavany', lead: 'Připravte si příjezd: doprava, elektřina, doklady a pravidla klidu.', highlights: [['Před příjezdem', 'Použijte Google Maps, protože vjezd se změnil v roce 2022. Připravte doklad totožnosti a registrační značku.'], ['V kempu', 'K dispozici je 10A elektřina, ne pro nabíjení elektromobilů. Těžká vozidla směřujeme na vhodný povrch.'], ['Pobyt', 'V červenci a srpnu jsou místa podle pořadí příjezdu. Odjezd z kempu do 12:00.']] },
  'dla-rodzin': { overline: 'Rodiny', title: 'Rodinný pobyt v Camping Clepardia', lead: 'Zelená městská základna pro návštěvu Krakova tramvají a klidný návrat.', highlights: [['Rytmus', 'Tramvaj je blízko, centrum navštívíte bez přesunu auta.'], ['Pravidla', 'Noční klid 22:00–07:00. Kemp není párty místo.'], ['Bungalovy', 'Příjezd od 16:00. Vezměte ručníky, hygienické potřeby a osobní věci.']] },
  regulamin: { overline: 'Pravidla', title: 'Pravidla pobytu', lead: 'Nejdůležitější pravidla před příjezdem do Camping Clepardia.', highlights: [['Klid', 'Noční klid 22:00–07:00; respektujte ostatní hosty.'], ['Doklady', 'Recepce může požádat o doklad totožnosti a registrační značky vozidla nebo karavanu.'], ['Zvířata', 'Psi jsou povoleni za 0 PLN; vždy po nich ukliďte.']] },
  'polityka-prywatnosci': { overline: 'Soukromí', title: 'Zásady ochrany soukromí', lead: 'Údaje slouží ke zpracování dotazů na pobyt a kontaktu s recepcí.', highlights: [['Kontakt', 'Kontaktní údaje používáme k odpovědi.'], ['Rezervace', 'Údaje o pobytu pomáhají ověřit dostupnost.'], ['Bezpečnost', 'Technická diagnostika se nezobrazuje ve veřejném rozhraní.']] },
});

Object.assign(corePages.sk.pages, {
  'dla-kamperow': { overline: 'Pre obytné autá', title: 'Informácie pre obytné autá a karavany', lead: 'Pripravte si príchod: doprava, elektrina, doklady a pravidlá pokoja.', highlights: [['Pred príchodom', 'Použite Google Maps, pretože vjazd sa zmenil v roku 2022. Pripravte doklad totožnosti a evidenčné číslo.'], ['V kempe', 'K dispozícii je 10A elektrina, nie na nabíjanie elektromobilov. Ťažké vozidlá smerujeme na vhodný povrch.'], ['Pobyt', 'V júli a auguste sú miesta podľa poradia príchodu. Odchod z kempu do 12:00.']] },
  'dla-rodzin': { overline: 'Rodiny', title: 'Rodinný pobyt v Camping Clepardia', lead: 'Zelená mestská základňa na návštevu Krakova električkou a pokojný návrat.', highlights: [['Rytmus', 'Električka je blízko, centrum navštívite bez presunu auta.'], ['Pravidlá', 'Nočný pokoj 22:00–07:00. Kemp nie je párty miesto.'], ['Bungalovy', 'Príchod od 16:00. Vezmite uteráky, hygienické potreby a osobné veci.']] },
  regulamin: { overline: 'Pravidlá', title: 'Pravidlá pobytu', lead: 'Najdôležitejšie pravidlá pred príchodom do Camping Clepardia.', highlights: [['Pokoj', 'Nočný pokoj 22:00–07:00; rešpektujte ostatných hostí.'], ['Doklady', 'Recepcia môže požiadať o doklad totožnosti a evidenčné čísla vozidla alebo karavanu.'], ['Zvieratá', 'Psy sú povolené za 0 PLN; vždy po nich upracte.']] },
  'polityka-prywatnosci': { overline: 'Súkromie', title: 'Zásady ochrany súkromia', lead: 'Údaje slúžia na spracovanie dopytov na pobyt a kontakt s recepciou.', highlights: [['Kontakt', 'Kontaktné údaje používame na odpoveď.'], ['Rezervácia', 'Údaje o pobyte pomáhajú overiť dostupnosť.'], ['Bezpečnosť', 'Technická diagnostika sa nezobrazuje vo verejnom rozhraní.']] },
});

Object.assign(corePages.sv.pages, {
  'dla-kamperow': { overline: 'För husbilar', title: 'Information för husbilar och husvagnar', lead: 'Förbered ankomst: väg, el, dokument och lugna campingregler.', highlights: [['Före ankomst', 'Använd Google Maps eftersom infarten ändrades 2022. Ha ID och registreringsnummer redo.'], ['På plats', '10A el finns, inte för laddning av elfordon. Tunga fordon hänvisas till lämpligt underlag.'], ['Vistelse', 'I juli och augusti gäller ankomstordning för campingplatser. Utcheckning camping senast 12.00.']] },
  'dla-rodzin': { overline: 'Familjer', title: 'Familjevistelse på Camping Clepardia', lead: 'En grön bas i staden för att besöka Kraków med spårvagn och komma tillbaka lugnt.', highlights: [['Tempo', 'Spårvagnen är nära, så centrum nås utan att flytta bilen.'], ['Regler', 'Nattro 22.00–07.00. Campingen är inte en festplats.'], ['Bungalower', 'Incheckning från 16.00. Ta med handdukar, hygienartiklar och personliga saker.']] },
  regulamin: { overline: 'Regler', title: 'Vistelseregler', lead: 'De viktigaste reglerna före ankomst till Camping Clepardia.', highlights: [['Lugn', 'Nattro 22.00–07.00; respektera andra gäster.'], ['Dokument', 'Receptionen kan be om ID och registreringsnummer för fordon eller husvagn.'], ['Djur', 'Hundar är välkomna för 0 PLN; plocka alltid upp efter hunden.']] },
  'polityka-prywatnosci': { overline: 'Integritet', title: 'Integritetspolicy', lead: 'Uppgifter används för vistelseförfrågningar och kontakt med receptionen.', highlights: [['Kontakt', 'Kontaktuppgifter används för att svara på din fråga.'], ['Bokning', 'Vistelseuppgifter hjälper receptionen att kontrollera tillgänglighet.'], ['Säkerhet', 'Teknisk diagnostik visas inte i offentlig UI.']] },
});

export const getCorePage = (language: string, slug: string) =>
  coreCustomerSlugs.includes(slug as CoreCustomerSlug)
    ? corePages[language]?.pages[slug as CoreCustomerSlug]
    : undefined;
