export type HomeAttractionKey = 'oldTown' | 'wawel' | 'kazimierz' | 'wieliczka' | 'auschwitz' | 'ojcow' | 'zakopane' | 'energylandia' | 'schindler' | 'waterPark';

type AttractionText = { name: string; description: string };

export interface HomeAttractionsToursCopy {
  kicker: string;
  title: string;
  lead: string;
  labels: {
    duration: string;
    travel: string;
    transport: string;
    booking: string;
    rain: string;
    family: string;
    details: string;
    tour: string;
    yes: string;
    limited: string;
  };
  practical: {
    city: string;
    halfDay: string;
    fullDay: string;
    tramWalk: string;
    tramBus: string;
    carBus: string;
    carTour: string;
    advance: string;
    recommended: string;
    optional: string;
  };
  items: Record<HomeAttractionKey, AttractionText>;
  auschwitz: {
    title: string;
    body: string;
    arrival: string;
    luggage: string;
    official: string;
    tour: string;
  };
  tours: {
    kicker: string;
    title: string;
    lead: string;
    availability: string;
    operator: string;
    noGuarantee: string;
    check: string;
    inquiry: string;
    campy: string;
  };
}

const pl: HomeAttractionsToursCopy = {
  kicker:'Kraków i Małopolska', title:'Atrakcje i wycieczki z Krakowa', lead:'Najważniejsze miejsca, praktyczne informacje i wygodne opcje zwiedzania z Krakowa.',
  labels:{ duration:'Czas',travel:'Dojazd z Clepardii',transport:'Transport',booking:'Rezerwacja',rain:'Na deszcz',family:'Dla rodzin',details:'Zobacz szczegóły',tour:'Sprawdź wycieczkę',yes:'Tak',limited:'Ograniczona liczba miejsc' },
  practical:{ city:'około 2–5 godzin',halfDay:'pół dnia',fullDay:'cały dzień',tramWalk:'tramwaj + spacer',tramBus:'tramwaj / bus',carBus:'samochód / bus',carTour:'samochód / wycieczka',advance:'konieczna wcześniej',recommended:'warto wcześniej',optional:'zwykle niepotrzebna' },
  items:{
    oldTown:{name:'Stare Miasto',description:'Rynek Główny, Sukiennice, bazylika Mariacka i Planty — najlepszy pierwszy spacer po Krakowie.'},
    wawel:{name:'Wawel',description:'Zamek, katedra i widok na Wisłę. Wnętrza mają osobne limity wejść, więc wybrane bilety warto kupić wcześniej.'},
    kazimierz:{name:'Kazimierz',description:'Historyczna dzielnica z synagogami, kawiarniami i dobrym planem na popołudnie lub wieczór.'},
    wieliczka:{name:'Kopalnia Soli Wieliczka',description:'Podziemna trasa, komory solne i historia kopalni. Popularne godziny wejścia mogą szybko znikać.'},
    auschwitz:{name:'Auschwitz-Birkenau',description:'Miejsce Pamięci wymagające spokojnego, całodniowego planu i obowiązkowej rezerwacji online.'},
    ojcow:{name:'Ojców',description:'Dolina Prądnika, wapienne skały i krótsze trasy w Ojcowskim Parku Narodowym.'},
    zakopane:{name:'Zakopane',description:'Całodniowy kierunek w Tatry — najlepiej z zapasem czasu na drogę i zmienną pogodę.'},
    energylandia:{name:'Energylandia',description:'Całodniowa atrakcja rodzinna; bilety online i plan dojazdu pomagają uniknąć kolejek.'},
    schindler:{name:'Fabryka Schindlera',description:'Muzeum historii Krakowa podczas okupacji i dobry plan na deszczowy dzień.'},
    waterPark:{name:'Park Wodny Kraków',description:'Rodzinny plan na kilka godzin i wygodna alternatywa na dzień z gorszą pogodą.'},
  },
  auschwitz:{ title:'Wizyta w Auschwitz-Birkenau wymaga wcześniejszej rezerwacji online',body:'Od 1 marca wszystkie karty wstępu są dostępne wyłącznie przez internet. Nie można otrzymać karty przy wejściu do Muzeum. Dotyczy to zarówno wizyt z przewodnikiem, jak i bezpłatnych kart wstępu. Liczba miejsc jest ograniczona, dlatego warto zarezerwować termin możliwie wcześnie.',arrival:'Przyjedź minimum 30 minut wcześniej ze względu na kontrolę bezpieczeństwa.',luggage:'Maksymalny rozmiar torby to 35 × 25 × 15 cm; większy bagaż zostaw w pojeździe.',official:'Oficjalne karty wstępu',tour:'Sprawdź wycieczkę z Krakowa' },
  tours:{ kicker:'Wygodna organizacja',title:'Wycieczki i transfery',lead:'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców i Energylandia są dostępne jako wyjazdy z Krakowa lub dojazd indywidualny.',availability:'Popularne terminy mogą szybko się wyprzedawać — warto sprawdzać je wcześniej.',operator:'Dostępność i ostateczne warunki potwierdza operator lub recepcja.',noGuarantee:'Camping Clepardia pomaga znaleźć opcje, ale nie gwarantuje miejsc ani wejścia.',check:'Sprawdź wycieczki',inquiry:'Dodaj wycieczkę do zapytania',campy:'Zapytaj CAMPY' },
};

const en: HomeAttractionsToursCopy = {
  kicker:'Krakow & Lesser Poland',title:'Attractions and tours from Krakow',lead:'Key places, practical information and convenient ways to explore from Krakow.',
  labels:{duration:'Time',travel:'From Clepardia',transport:'Transport',booking:'Booking',rain:'Rainy day',family:'Families',details:'See details',tour:'Check a tour',yes:'Yes',limited:'Limited availability'},
  practical:{city:'about 2–5 hours',halfDay:'half day',fullDay:'full day',tramWalk:'tram + walk',tramBus:'tram / bus',carBus:'car / bus',carTour:'car / organised tour',advance:'required in advance',recommended:'book ahead',optional:'usually not needed'},
  items:{oldTown:{name:'Old Town',description:'Main Square, Cloth Hall, St Mary’s Basilica and Planty — the best first walk through Krakow.'},wawel:{name:'Wawel',description:'Royal Castle, cathedral and Vistula views. Selected interiors have timed entry.'},kazimierz:{name:'Kazimierz',description:'Historic district with synagogues, cafés and an easy afternoon or evening route.'},wieliczka:{name:'Wieliczka Salt Mine',description:'Underground route, salt chambers and mining history. Popular time slots sell quickly.'},auschwitz:{name:'Auschwitz-Birkenau',description:'A Memorial visit requiring a calm full-day plan and mandatory online reservation.'},ojcow:{name:'Ojców',description:'Prądnik Valley, limestone rocks and shorter routes in Ojców National Park.'},zakopane:{name:'Zakopane',description:'A full-day Tatra destination with extra time needed for travel and changing weather.'},energylandia:{name:'Energylandia',description:'A full family day; online tickets and a transport plan help avoid queues.'},schindler:{name:'Schindler’s Factory',description:'Museum of Krakow under occupation and a good option for a rainy day.'},waterPark:{name:'Krakow Water Park',description:'A family plan for a few hours and a convenient bad-weather alternative.'}},
  auschwitz:{title:'A visit to Auschwitz-Birkenau requires advance online reservation',body:'From 1 March, all entry cards are available only online. No entry card can be obtained at the Museum entrance. This applies to guided visits and free entry cards. Places are limited, so reserve as early as possible.',arrival:'Arrive at least 30 minutes early for security checks.',luggage:'Maximum bag size is 35 × 25 × 15 cm; leave larger luggage in your vehicle.',official:'Official entry cards',tour:'Check a tour from Krakow'},
  tours:{kicker:'Easy planning',title:'Tours and transfers',lead:'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców and Energylandia can be visited on organised trips or independently.',availability:'Popular dates can sell out quickly — check them early.',operator:'Availability and final conditions are confirmed by the operator or reception.',noGuarantee:'Camping Clepardia helps compare options but cannot guarantee places or admission.',check:'Check tours',inquiry:'Add a tour to your enquiry',campy:'Ask CAMPY'},
};

const de: HomeAttractionsToursCopy = {
  ...en,kicker:'Krakau & Kleinpolen',title:'Sehenswürdigkeiten und Ausflüge ab Krakau',lead:'Wichtige Orte, praktische Hinweise und bequeme Ausflugsmöglichkeiten ab Krakau.',labels:{duration:'Zeit',travel:'Ab Clepardia',transport:'Verkehr',booking:'Reservierung',rain:'Bei Regen',family:'Familien',details:'Details ansehen',tour:'Ausflug prüfen',yes:'Ja',limited:'Begrenzte Plätze'},practical:{city:'ca. 2–5 Stunden',halfDay:'halber Tag',fullDay:'ganzer Tag',tramWalk:'Straßenbahn + zu Fuß',tramBus:'Straßenbahn / Bus',carBus:'Auto / Bus',carTour:'Auto / organisierter Ausflug',advance:'vorher erforderlich',recommended:'vorher buchen',optional:'meist nicht nötig'},
  items:{oldTown:{name:'Altstadt',description:'Hauptmarkt, Tuchhallen, Marienkirche und Planty — der beste erste Spaziergang durch Krakau.'},wawel:{name:'Wawel',description:'Königsschloss, Kathedrale und Weichselblick. Einige Innenräume haben Zeitfenster.'},kazimierz:{name:'Kazimierz',description:'Historisches Viertel mit Synagogen, Cafés und einer guten Nachmittagsroute.'},wieliczka:{name:'Salzbergwerk Wieliczka',description:'Unterirdische Route, Salzräume und Bergbaugeschichte. Beliebte Zeiten sind schnell weg.'},auschwitz:{name:'Auschwitz-Birkenau',description:'Ein Besuch der Gedenkstätte braucht einen ruhigen Tagesplan und eine Online-Reservierung.'},ojcow:{name:'Ojców',description:'Prądnik-Tal, Kalkfelsen und kurze Routen im Nationalpark Ojców.'},zakopane:{name:'Zakopane',description:'Ganztagesziel in der Tatra mit Zeitreserve für Fahrt und Wetter.'},energylandia:{name:'Energylandia',description:'Ein ganzer Familientag; Online-Tickets und Anreiseplan sparen Wartezeit.'},schindler:{name:'Schindlers Fabrik',description:'Museum über Krakau während der Besatzung und eine gute Regenoption.'},waterPark:{name:'Wasserpark Krakau',description:'Familienprogramm für einige Stunden und Alternative bei schlechtem Wetter.'}},
  auschwitz:{title:'Für Auschwitz-Birkenau ist eine vorherige Online-Reservierung erforderlich',body:'Seit 1. März sind alle Eintrittskarten ausschließlich online erhältlich. Am Museumseingang gibt es keine Eintrittskarten. Das gilt für Führungen und kostenlose Eintrittskarten. Die Plätze sind begrenzt; reservieren Sie möglichst früh.',arrival:'Mindestens 30 Minuten vor Beginn wegen der Sicherheitskontrolle ankommen.',luggage:'Maximale Taschengröße: 35 × 25 × 15 cm; größeres Gepäck im Fahrzeug lassen.',official:'Offizielle Eintrittskarten',tour:'Ausflug ab Krakau prüfen'},
  tours:{kicker:'Bequem planen',title:'Ausflüge und Transfers',lead:'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców und Energylandia sind organisiert oder individuell erreichbar.',availability:'Beliebte Termine können schnell ausgebucht sein.',operator:'Verfügbarkeit und Bedingungen bestätigt der Anbieter oder die Rezeption.',noGuarantee:'Camping Clepardia hilft beim Vergleich, garantiert aber weder Plätze noch Eintritt.',check:'Ausflüge prüfen',inquiry:'Ausflug zur Anfrage hinzufügen',campy:'CAMPY fragen'},
};

const it: HomeAttractionsToursCopy = {
  ...en,kicker:'Cracovia e Piccola Polonia',title:'Attrazioni e tour da Cracovia',lead:'Luoghi principali, informazioni pratiche e modi comodi per esplorare partendo da Cracovia.',labels:{duration:'Tempo',travel:'Da Clepardia',transport:'Trasporto',booking:'Prenotazione',rain:'Con pioggia',family:'Famiglie',details:'Vedi dettagli',tour:'Controlla tour',yes:'Sì',limited:'Posti limitati'},practical:{city:'circa 2–5 ore',halfDay:'mezza giornata',fullDay:'giornata intera',tramWalk:'tram + passeggiata',tramBus:'tram / bus',carBus:'auto / bus',carTour:'auto / tour organizzato',advance:'obbligatoria prima',recommended:'prenota prima',optional:'di solito non serve'},
  items:{oldTown:{name:'Città Vecchia',description:'Rynek, Sukiennice, basilica di Santa Maria e Planty: la prima passeggiata ideale.'},wawel:{name:'Wawel',description:'Castello reale, cattedrale e vista sulla Vistola. Alcuni interni hanno ingressi a orario.'},kazimierz:{name:'Kazimierz',description:'Quartiere storico con sinagoghe, caffè e un buon itinerario pomeridiano.'},wieliczka:{name:'Miniera di Sale Wieliczka',description:'Percorso sotterraneo, sale di sale e storia mineraria. Gli orari popolari finiscono presto.'},auschwitz:{name:'Auschwitz-Birkenau',description:'La visita al Memoriale richiede una giornata tranquilla e prenotazione online obbligatoria.'},ojcow:{name:'Ojców',description:'Valle del Prądnik, rocce calcaree e percorsi brevi nel parco nazionale.'},zakopane:{name:'Zakopane',description:'Meta giornaliera sui Tatra con margine per viaggio e meteo.'},energylandia:{name:'Energylandia',description:'Giornata in famiglia; biglietti online e trasporto pianificato riducono le code.'},schindler:{name:'Fabbrica di Schindler',description:'Museo della Cracovia occupata e buona scelta con la pioggia.'},waterPark:{name:'Parco Acquatico di Cracovia',description:'Piano familiare di alcune ore e alternativa con brutto tempo.'}},
  auschwitz:{title:'La visita ad Auschwitz-Birkenau richiede una prenotazione online anticipata',body:'Dal 1° marzo tutte le carte d’ingresso sono disponibili solo online. Non si possono ottenere all’ingresso del Museo. Vale per visite guidate e carte gratuite. I posti sono limitati: prenota il prima possibile.',arrival:'Arriva almeno 30 minuti prima per i controlli di sicurezza.',luggage:'Borsa massima 35 × 25 × 15 cm; lascia i bagagli più grandi nel veicolo.',official:'Carte d’ingresso ufficiali',tour:'Controlla un tour da Cracovia'},
  tours:{kicker:'Organizzazione semplice',title:'Tour e transfer',lead:'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców ed Energylandia sono raggiungibili con tour o in autonomia.',availability:'Le date popolari possono esaurirsi rapidamente.',operator:'Disponibilità e condizioni finali sono confermate dall’operatore o dalla reception.',noGuarantee:'Camping Clepardia aiuta a confrontare le opzioni ma non garantisce posti o ingresso.',check:'Controlla tour',inquiry:'Aggiungi un tour alla richiesta',campy:'Chiedi a CAMPY'},
};

const fr: HomeAttractionsToursCopy = {
  ...en,kicker:'Cracovie et Petite-Pologne',title:'Attractions et excursions depuis Cracovie',lead:'Les lieux essentiels, des informations pratiques et des options simples depuis Cracovie.',labels:{duration:'Durée',travel:'Depuis Clepardia',transport:'Transport',booking:'Réservation',rain:'Par pluie',family:'Familles',details:'Voir les détails',tour:'Voir l’excursion',yes:'Oui',limited:'Places limitées'},practical:{city:'environ 2–5 heures',halfDay:'demi-journée',fullDay:'journée entière',tramWalk:'tramway + marche',tramBus:'tramway / bus',carBus:'voiture / bus',carTour:'voiture / excursion',advance:'obligatoire avant',recommended:'réserver avant',optional:'souvent inutile'},
  items:{oldTown:{name:'Vieille Ville',description:'Rynek, Halle aux Draps, basilique Sainte-Marie et Planty : la première promenade idéale.'},wawel:{name:'Wawel',description:'Château royal, cathédrale et Vistule. Certains intérieurs ont des créneaux.'},kazimierz:{name:'Kazimierz',description:'Quartier historique, synagogues, cafés et parcours idéal l’après-midi.'},wieliczka:{name:'Mine de sel Wieliczka',description:'Parcours souterrain, chambres de sel et histoire minière. Les créneaux partent vite.'},auschwitz:{name:'Auschwitz-Birkenau',description:'La visite du Mémorial demande une journée calme et une réservation en ligne obligatoire.'},ojcow:{name:'Ojców',description:'Vallée du Prądnik, rochers calcaires et itinéraires courts dans le parc national.'},zakopane:{name:'Zakopane',description:'Destination dans les Tatras pour la journée, avec marge pour trajet et météo.'},energylandia:{name:'Energylandia',description:'Journée familiale ; billets en ligne et trajet préparé réduisent les files.'},schindler:{name:'Usine Schindler',description:'Musée de Cracovie sous l’occupation et bonne option par pluie.'},waterPark:{name:'Parc aquatique de Cracovie',description:'Quelques heures en famille et une alternative par mauvais temps.'}},
  auschwitz:{title:'La visite d’Auschwitz-Birkenau exige une réservation en ligne préalable',body:'Depuis le 1er mars, toutes les cartes d’entrée sont disponibles uniquement en ligne. Aucune carte n’est délivrée à l’entrée du Musée. Cela concerne les visites guidées et les cartes gratuites. Les places sont limitées : réservez au plus tôt.',arrival:'Arrivez au moins 30 minutes avant pour les contrôles de sécurité.',luggage:'Sac maximum 35 × 25 × 15 cm ; laissez les bagages plus grands dans le véhicule.',official:'Cartes d’entrée officielles',tour:'Voir une excursion depuis Cracovie'},
  tours:{kicker:'Organisation facile',title:'Excursions et transferts',lead:'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców et Energylandia sont accessibles en excursion ou librement.',availability:'Les dates populaires peuvent vite être complètes.',operator:'La disponibilité et les conditions sont confirmées par l’opérateur ou la réception.',noGuarantee:'Camping Clepardia aide à comparer, sans garantir place ni entrée.',check:'Voir les excursions',inquiry:'Ajouter une excursion à la demande',campy:'Demander à CAMPY'},
};

const es: HomeAttractionsToursCopy = {
  ...en,kicker:'Cracovia y Pequeña Polonia',title:'Atracciones y excursiones desde Cracovia',lead:'Lugares clave, información práctica y opciones cómodas para conocer la región.',labels:{duration:'Tiempo',travel:'Desde Clepardia',transport:'Transporte',booking:'Reserva',rain:'Con lluvia',family:'Familias',details:'Ver detalles',tour:'Ver excursión',yes:'Sí',limited:'Plazas limitadas'},practical:{city:'unas 2–5 horas',halfDay:'medio día',fullDay:'día completo',tramWalk:'tranvía + paseo',tramBus:'tranvía / bus',carBus:'coche / bus',carTour:'coche / excursión',advance:'obligatoria antes',recommended:'reservar antes',optional:'normalmente no'},
  items:{oldTown:{name:'Casco antiguo',description:'Rynek, Sukiennice, basílica de Santa María y Planty: el primer paseo ideal.'},wawel:{name:'Wawel',description:'Castillo real, catedral y vistas al Vístula. Algunos interiores tienen horario.'},kazimierz:{name:'Kazimierz',description:'Barrio histórico con sinagogas, cafés y una buena ruta de tarde.'},wieliczka:{name:'Mina de Sal Wieliczka',description:'Ruta subterránea, cámaras de sal e historia minera. Los horarios populares se agotan.'},auschwitz:{name:'Auschwitz-Birkenau',description:'La visita al Memorial requiere un día tranquilo y reserva online obligatoria.'},ojcow:{name:'Ojców',description:'Valle del Prądnik, roca caliza y rutas cortas por el parque nacional.'},zakopane:{name:'Zakopane',description:'Destino de día completo en los Tatras con margen para viaje y clima.'},energylandia:{name:'Energylandia',description:'Día familiar; entradas online y transporte preparado reducen colas.'},schindler:{name:'Fábrica de Schindler',description:'Museo sobre Cracovia durante la ocupación y buena opción con lluvia.'},waterPark:{name:'Parque Acuático de Cracovia',description:'Plan familiar de unas horas y alternativa con mal tiempo.'}},
  auschwitz:{title:'La visita a Auschwitz-Birkenau requiere reserva online previa',body:'Desde el 1 de marzo, todas las tarjetas de entrada están disponibles únicamente online. No se pueden obtener en la entrada del Museo. Se aplica a visitas guiadas y entradas gratuitas. Las plazas son limitadas: reserva cuanto antes.',arrival:'Llega al menos 30 minutos antes por los controles de seguridad.',luggage:'Bolso máximo 35 × 25 × 15 cm; deja equipaje mayor en el vehículo.',official:'Entradas oficiales',tour:'Ver excursión desde Cracovia'},
  tours:{kicker:'Organización sencilla',title:'Excursiones y traslados',lead:'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców y Energylandia pueden visitarse en tour o por cuenta propia.',availability:'Las fechas populares pueden agotarse rápido.',operator:'La disponibilidad y condiciones finales las confirma el operador o recepción.',noGuarantee:'Camping Clepardia ayuda a comparar, pero no garantiza plazas ni entrada.',check:'Ver excursiones',inquiry:'Añadir excursión a la consulta',campy:'Preguntar a CAMPY'},
};

const nl: HomeAttractionsToursCopy = {
  ...en,kicker:'Krakau en Klein-Polen',title:'Bezienswaardigheden en tours vanuit Krakau',lead:'Belangrijke plekken, praktische informatie en makkelijke opties vanuit Krakau.',labels:{duration:'Tijd',travel:'Vanaf Clepardia',transport:'Vervoer',booking:'Reservering',rain:'Bij regen',family:'Gezinnen',details:'Bekijk details',tour:'Bekijk tour',yes:'Ja',limited:'Beperkte plaatsen'},practical:{city:'ongeveer 2–5 uur',halfDay:'halve dag',fullDay:'hele dag',tramWalk:'tram + lopen',tramBus:'tram / bus',carBus:'auto / bus',carTour:'auto / georganiseerde tour',advance:'vooraf verplicht',recommended:'vooraf boeken',optional:'meestal niet nodig'},
  items:{oldTown:{name:'Oude Stad',description:'Marktplein, Lakenhal, Mariakerk en Planty — de beste eerste wandeling.'},wawel:{name:'Wawel',description:'Koninklijk kasteel, kathedraal en uitzicht op de Wisła. Sommige delen hebben tijdsloten.'},kazimierz:{name:'Kazimierz',description:'Historische wijk met synagogen, cafés en een fijne middagroute.'},wieliczka:{name:'Zoutmijn Wieliczka',description:'Ondergrondse route, zoutkamers en mijngeschiedenis. Populaire tijden raken vol.'},auschwitz:{name:'Auschwitz-Birkenau',description:'Een bezoek aan het Memorial vraagt een rustige dag en verplichte online reservering.'},ojcow:{name:'Ojców',description:'Prądnikvallei, kalkrotsen en korte routes in het nationale park.'},zakopane:{name:'Zakopane',description:'Dagbestemming in de Tatra met extra tijd voor reis en weer.'},energylandia:{name:'Energylandia',description:'Een familiedag; online tickets en een reisplan helpen wachtrijen beperken.'},schindler:{name:'Schindlerfabriek',description:'Museum over bezet Krakau en een goede keuze bij regen.'},waterPark:{name:'Waterpark Krakau',description:'Een paar uur met het gezin en alternatief bij slecht weer.'}},
  auschwitz:{title:'Een bezoek aan Auschwitz-Birkenau vereist vooraf online reserveren',body:'Vanaf 1 maart zijn alle toegangsbewijzen uitsluitend online beschikbaar. Bij de ingang van het Museum zijn geen kaarten verkrijgbaar. Dit geldt voor rondleidingen en gratis kaarten. Plaatsen zijn beperkt; reserveer zo vroeg mogelijk.',arrival:'Kom minstens 30 minuten eerder voor de veiligheidscontrole.',luggage:'Maximale tas 35 × 25 × 15 cm; laat grotere bagage in het voertuig.',official:'Officiële toegangsbewijzen',tour:'Bekijk tour vanuit Krakau'},
  tours:{kicker:'Makkelijk plannen',title:'Tours en transfers',lead:'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców en Energylandia zijn georganiseerd of zelfstandig bereikbaar.',availability:'Populaire data kunnen snel vol raken.',operator:'Beschikbaarheid en voorwaarden worden bevestigd door aanbieder of receptie.',noGuarantee:'Camping Clepardia helpt vergelijken, maar garandeert geen plaats of toegang.',check:'Bekijk tours',inquiry:'Voeg tour toe aan aanvraag',campy:'Vraag CAMPY'},
};

const cs: HomeAttractionsToursCopy = {
  ...en,kicker:'Krakov a Malopolsko',title:'Atrakce a výlety z Krakova',lead:'Nejdůležitější místa, praktické informace a pohodlné možnosti výletů.',labels:{duration:'Čas',travel:'Z Clepardie',transport:'Doprava',booking:'Rezervace',rain:'Za deště',family:'Rodiny',details:'Zobrazit detaily',tour:'Zkontrolovat výlet',yes:'Ano',limited:'Omezená místa'},practical:{city:'asi 2–5 hodin',halfDay:'půl dne',fullDay:'celý den',tramWalk:'tramvaj + pěšky',tramBus:'tramvaj / bus',carBus:'auto / bus',carTour:'auto / organizovaný výlet',advance:'nutná předem',recommended:'rezervovat předem',optional:'většinou není nutná'},
  items:{oldTown:{name:'Staré Město',description:'Rynek, Sukiennice, Mariánský kostel a Planty — nejlepší první procházka.'},wawel:{name:'Wawel',description:'Královský hrad, katedrála a výhled na Vislu. Některé interiéry mají časové vstupy.'},kazimierz:{name:'Kazimierz',description:'Historická čtvrť se synagogami, kavárnami a příjemnou odpolední trasou.'},wieliczka:{name:'Solný důl Wieliczka',description:'Podzemní trasa, solné komory a historie dolu. Oblíbené časy rychle mizí.'},auschwitz:{name:'Auschwitz-Birkenau',description:'Návštěva památníku vyžaduje klidný den a povinnou online rezervaci.'},ojcow:{name:'Ojców',description:'Údolí Prądniku, vápencové skály a kratší trasy v národním parku.'},zakopane:{name:'Zakopane',description:'Celodenní cíl v Tatrách s rezervou na dopravu a počasí.'},energylandia:{name:'Energylandia',description:'Rodinný den; online vstupenky a plán dopravy pomohou omezit fronty.'},schindler:{name:'Schindlerova továrna',description:'Muzeum okupovaného Krakova a dobrá volba za deště.'},waterPark:{name:'Aquapark Krakov',description:'Několik hodin pro rodinu a alternativa za špatného počasí.'}},
  auschwitz:{title:'Návštěva Auschwitz-Birkenau vyžaduje předchozí online rezervaci',body:'Od 1. března jsou všechny vstupní karty dostupné pouze online. U vstupu do Muzea je nelze získat. Platí to pro prohlídky s průvodcem i bezplatné karty. Počet míst je omezený; rezervujte co nejdříve.',arrival:'Přijeďte alespoň 30 minut předem kvůli bezpečnostní kontrole.',luggage:'Maximální taška 35 × 25 × 15 cm; větší zavazadla nechte ve vozidle.',official:'Oficiální vstupní karty',tour:'Zkontrolovat výlet z Krakova'},
  tours:{kicker:'Snadné plánování',title:'Výlety a transfery',lead:'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców a Energylandia jsou dostupné organizovaně i samostatně.',availability:'Oblíbené termíny se mohou rychle vyprodat.',operator:'Dostupnost a podmínky potvrzuje provozovatel nebo recepce.',noGuarantee:'Camping Clepardia pomůže porovnat možnosti, ale negarantuje místo ani vstup.',check:'Zkontrolovat výlety',inquiry:'Přidat výlet k dotazu',campy:'Zeptat se CAMPY'},
};

const sk: HomeAttractionsToursCopy = {
  ...cs,kicker:'Krakov a Malopoľsko',title:'Atrakcie a výlety z Krakova',lead:'Najdôležitejšie miesta, praktické informácie a pohodlné možnosti výletov.',labels:{duration:'Čas',travel:'Z Clepardie',transport:'Doprava',booking:'Rezervácia',rain:'Za dažďa',family:'Rodiny',details:'Zobraziť detaily',tour:'Skontrolovať výlet',yes:'Áno',limited:'Obmedzené miesta'},practical:{city:'asi 2–5 hodín',halfDay:'pol dňa',fullDay:'celý deň',tramWalk:'električka + pešo',tramBus:'električka / bus',carBus:'auto / bus',carTour:'auto / organizovaný výlet',advance:'nutná vopred',recommended:'rezervovať vopred',optional:'väčšinou netreba'},
  items:{oldTown:{name:'Staré Mesto',description:'Rynek, Sukiennice, Mariánsky kostol a Planty — najlepšia prvá prechádzka.'},wawel:{name:'Wawel',description:'Kráľovský hrad, katedrála a výhľad na Vislu. Niektoré interiéry majú časové vstupy.'},kazimierz:{name:'Kazimierz',description:'Historická štvrť so synagógami, kaviarňami a príjemnou trasou.'},wieliczka:{name:'Soľná baňa Wieliczka',description:'Podzemná trasa, soľné komory a história bane. Populárne časy sa rýchlo míňajú.'},auschwitz:{name:'Auschwitz-Birkenau',description:'Návšteva pamätníka vyžaduje pokojný deň a povinnú online rezerváciu.'},ojcow:{name:'Ojców',description:'Údolie Prądnika, vápencové skaly a kratšie trasy v národnom parku.'},zakopane:{name:'Zakopane',description:'Celodenný cieľ v Tatrách s rezervou na dopravu a počasie.'},energylandia:{name:'Energylandia',description:'Rodinný deň; online vstupenky a plán dopravy pomôžu obmedziť rady.'},schindler:{name:'Schindlerova továreň',description:'Múzeum okupovaného Krakova a dobrá voľba za dažďa.'},waterPark:{name:'Aquapark Krakov',description:'Niekoľko hodín pre rodinu a alternatíva za zlého počasia.'}},
  auschwitz:{title:'Návšteva Auschwitz-Birkenau vyžaduje predchádzajúcu online rezerváciu',body:'Od 1. marca sú všetky vstupné karty dostupné iba online. Pri vstupe do Múzea ich nemožno získať. Platí to pre prehliadky so sprievodcom aj bezplatné karty. Miesta sú obmedzené; rezervujte čo najskôr.',arrival:'Príďte aspoň 30 minút vopred kvôli bezpečnostnej kontrole.',luggage:'Maximálna taška 35 × 25 × 15 cm; väčšiu batožinu nechajte vo vozidle.',official:'Oficiálne vstupné karty',tour:'Skontrolovať výlet z Krakova'},
  tours:{kicker:'Jednoduché plánovanie',title:'Výlety a transfery',lead:'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców a Energylandia sú dostupné organizovane aj samostatne.',availability:'Populárne termíny sa môžu rýchlo vypredať.',operator:'Dostupnosť a podmienky potvrdzuje operátor alebo recepcia.',noGuarantee:'Camping Clepardia pomôže porovnať možnosti, ale negarantuje miesto ani vstup.',check:'Skontrolovať výlety',inquiry:'Pridať výlet k dopytu',campy:'Opýtať sa CAMPY'},
};

const sv: HomeAttractionsToursCopy = {
  ...en,kicker:'Kraków och Lillpolen',title:'Sevärdheter och turer från Kraków',lead:'Viktiga platser, praktisk information och smidiga sätt att upptäcka regionen.',labels:{duration:'Tid',travel:'Från Clepardia',transport:'Transport',booking:'Bokning',rain:'Vid regn',family:'Familjer',details:'Se detaljer',tour:'Kontrollera tur',yes:'Ja',limited:'Begränsat antal platser'},practical:{city:'cirka 2–5 timmar',halfDay:'halvdag',fullDay:'heldag',tramWalk:'spårvagn + promenad',tramBus:'spårvagn / buss',carBus:'bil / buss',carTour:'bil / organiserad tur',advance:'krävs i förväg',recommended:'boka i förväg',optional:'vanligen inte nödvändig'},
  items:{oldTown:{name:'Gamla stan',description:'Stora torget, Sukiennice, Mariakyrkan och Planty — den bästa första promenaden.'},wawel:{name:'Wawel',description:'Kungliga slottet, katedralen och utsikt över Wisła. Vissa interiörer har tider.'},kazimierz:{name:'Kazimierz',description:'Historiskt område med synagogor, kaféer och en bra eftermiddagsrutt.'},wieliczka:{name:'Wieliczka saltgruva',description:'Underjordisk rutt, saltkammare och gruvhistoria. Populära tider blir snabbt fulla.'},auschwitz:{name:'Auschwitz-Birkenau',description:'Ett besök på minnesplatsen kräver en lugn heldag och obligatorisk onlinebokning.'},ojcow:{name:'Ojców',description:'Prądnikdalen, kalkstensklippor och kortare leder i nationalparken.'},zakopane:{name:'Zakopane',description:'Heldagsmål i Tatra med marginal för resa och väder.'},energylandia:{name:'Energylandia',description:'En familjedag; onlinebiljetter och reseplan minskar köer.'},schindler:{name:'Schindlers fabrik',description:'Museum om det ockuperade Kraków och ett bra regnalternativ.'},waterPark:{name:'Vattenpark Kraków',description:'Några timmar för familjen och alternativ vid dåligt väder.'}},
  auschwitz:{title:'Ett besök i Auschwitz-Birkenau kräver förhandsbokning online',body:'Från 1 mars finns alla inträdeskort endast online. Inga kort kan erhållas vid museets entré. Detta gäller guidade besök och kostnadsfria kort. Antalet platser är begränsat; boka så tidigt som möjligt.',arrival:'Kom minst 30 minuter tidigare för säkerhetskontrollen.',luggage:'Maximal väska 35 × 25 × 15 cm; lämna större bagage i fordonet.',official:'Officiella inträdeskort',tour:'Kontrollera tur från Kraków'},
  tours:{kicker:'Smidig planering',title:'Turer och transfer',lead:'Wieliczka, Auschwitz-Birkenau, Zakopane, Ojców och Energylandia nås organiserat eller på egen hand.',availability:'Populära datum kan snabbt bli fulla.',operator:'Tillgänglighet och villkor bekräftas av operatören eller receptionen.',noGuarantee:'Camping Clepardia hjälper jämföra men garanterar inte plats eller inträde.',check:'Kontrollera turer',inquiry:'Lägg till tur i förfrågan',campy:'Fråga CAMPY'},
};

const copies = { pl,en,de,it,fr,es,nl,cs,sk,sv } satisfies Record<string,HomeAttractionsToursCopy>;

export const getHomeAttractionsToursCopy = (language = 'pl') => copies[language as keyof typeof copies] ?? copies.en;

