export type WeatherLanguage = 'pl' | 'en' | 'de' | 'it' | 'fr' | 'es' | 'nl' | 'cs' | 'sk' | 'sv';

export const weatherLanguages: WeatherLanguage[] = ['pl', 'en', 'de', 'it', 'fr', 'es', 'nl', 'cs', 'sk', 'sv'];

export const weatherCopy = {
  pl: { title:'Pogoda w Krakowie', heroLocation:'Kraków · teraz', heroUnavailable:'Prognoza chwilowo niedostępna', live:'Warunki przy campingu', loading:'Sprawdzamy aktualną pogodę…', unavailable:'Nie udało się teraz pobrać pogody. Plan pobytu nadal działa — sprawdź prognozę ponownie za chwilę.', feels:'odczuwalna', rain:'opady', wind:'wiatr', uv:'UV', details:'Dopasuj plan do pogody', forecast:'Prognoza', exactLater:'Dokładna prognoza pojawi się bliżej przyjazdu.', conditions:{ clear:'bezchmurnie', mostlyClear:'przeważnie słonecznie', cloudy:'pochmurno', fog:'mgła', drizzle:'mżawka', rain:'deszcz', snow:'śnieg', storm:'burza' }, tips:{ tentRain:'Możliwy deszcz — warto zabezpieczyć namiot.', heat:'Wysokie temperatury — zabierz wodę i nakrycie głowy.', uv:'Warto użyć kremu z filtrem.', camper:'Warunki dojazdu wyglądają spokojnie.', wind:'Zabezpiecz markizę i lekkie wyposażenie.' } },
  en: { title:'Weather in Krakow', heroLocation:'Krakow · now', heroUnavailable:'Forecast temporarily unavailable', live:'Conditions by the campsite', loading:'Checking the latest weather…', unavailable:'We could not fetch the weather right now. Your stay plan still works — please check the forecast again in a moment.', feels:'feels like', rain:'rain', wind:'wind', uv:'UV', details:'Match your plan to the weather', forecast:'Forecast', exactLater:'The detailed forecast will appear closer to arrival.', conditions:{ clear:'clear', mostlyClear:'mostly sunny', cloudy:'cloudy', fog:'fog', drizzle:'drizzle', rain:'rain', snow:'snow', storm:'thunderstorm' }, tips:{ tentRain:'Rain is possible — secure your tent.', heat:'High temperatures — take water and a sun hat.', uv:'Use sunscreen.', camper:'Driving conditions look calm.', wind:'Secure the awning and light equipment.' } },
  de: { title:'Wetter in Krakau', heroLocation:'Krakau · jetzt', heroUnavailable:'Vorhersage derzeit nicht verfügbar', live:'Wetter am Campingplatz', loading:'Aktuelles Wetter wird geprüft…', unavailable:'Das Wetter konnte gerade nicht geladen werden. Ihr Aufenthaltsplan funktioniert weiterhin — prüfen Sie die Vorhersage bitte gleich noch einmal.', feels:'gefühlt', rain:'Regen', wind:'Wind', uv:'UV', details:'Plan ans Wetter anpassen', forecast:'Vorhersage', exactLater:'Die genaue Vorhersage erscheint näher an der Anreise.', conditions:{ clear:'klar', mostlyClear:'überwiegend sonnig', cloudy:'bewölkt', fog:'Nebel', drizzle:'Nieselregen', rain:'Regen', snow:'Schnee', storm:'Gewitter' }, tips:{ tentRain:'Regen ist möglich — bitte das Zelt sichern.', heat:'Hohe Temperaturen — Wasser und Kopfbedeckung mitnehmen.', uv:'Sonnenschutz verwenden.', camper:'Die Anreisebedingungen wirken ruhig.', wind:'Markise und leichte Ausrüstung sichern.' } },
  it: { title:'Meteo a Cracovia', heroLocation:'Cracovia · ora', heroUnavailable:'Previsioni momentaneamente non disponibili', live:'Condizioni al camping', loading:'Controllo del meteo aggiornato…', unavailable:'Non è stato possibile caricare il meteo. Il piano di soggiorno continua a funzionare — riprova tra poco.', feels:'percepita', rain:'pioggia', wind:'vento', uv:'UV', details:'Adatta il piano al meteo', forecast:'Previsioni', exactLater:'Le previsioni precise appariranno più vicino all’arrivo.', conditions:{ clear:'sereno', mostlyClear:'prevalentemente soleggiato', cloudy:'nuvoloso', fog:'nebbia', drizzle:'pioviggine', rain:'pioggia', snow:'neve', storm:'temporale' }, tips:{ tentRain:'Possibile pioggia — proteggi bene la tenda.', heat:'Temperature alte — porta acqua e cappello.', uv:'Usa la crema solare.', camper:'Le condizioni di arrivo sembrano tranquille.', wind:'Fissa tendalino e attrezzatura leggera.' } },
  fr: { title:'Météo à Cracovie', heroLocation:'Cracovie · maintenant', heroUnavailable:'Prévisions momentanément indisponibles', live:'Conditions près du camping', loading:'Vérification de la météo…', unavailable:'Impossible de charger la météo pour le moment. Votre programme fonctionne toujours — réessayez dans un instant.', feels:'ressenti', rain:'pluie', wind:'vent', uv:'UV', details:'Adapter le programme à la météo', forecast:'Prévisions', exactLater:'Les prévisions précises apparaîtront à l’approche de l’arrivée.', conditions:{ clear:'ciel dégagé', mostlyClear:'plutôt ensoleillé', cloudy:'nuageux', fog:'brouillard', drizzle:'bruine', rain:'pluie', snow:'neige', storm:'orage' }, tips:{ tentRain:'Pluie possible — protégez bien la tente.', heat:'Températures élevées — prenez de l’eau et un chapeau.', uv:'Utilisez une protection solaire.', camper:'Les conditions d’accès semblent calmes.', wind:'Fixez l’auvent et le matériel léger.' } },
  es: { title:'Tiempo en Cracovia', heroLocation:'Cracovia · ahora', heroUnavailable:'Previsión temporalmente no disponible', live:'Condiciones junto al camping', loading:'Consultando el tiempo actual…', unavailable:'No se ha podido cargar el tiempo. Tu plan de estancia sigue funcionando — vuelve a consultar la previsión en unos minutos.', feels:'sensación', rain:'lluvia', wind:'viento', uv:'UV', details:'Adapta el plan al tiempo', forecast:'Previsión', exactLater:'La previsión detallada aparecerá más cerca de la llegada.', conditions:{ clear:'despejado', mostlyClear:'mayormente soleado', cloudy:'nublado', fog:'niebla', drizzle:'llovizna', rain:'lluvia', snow:'nieve', storm:'tormenta' }, tips:{ tentRain:'Puede llover — protege bien la tienda.', heat:'Temperaturas altas — lleva agua y gorra.', uv:'Usa protector solar.', camper:'Las condiciones de acceso parecen tranquilas.', wind:'Asegura el toldo y el equipo ligero.' } },
  nl: { title:'Weer in Krakau', heroLocation:'Krakau · nu', heroUnavailable:'Verwachting tijdelijk niet beschikbaar', live:'Omstandigheden bij de camping', loading:'Actueel weer wordt opgehaald…', unavailable:'Het weer kon nu niet worden opgehaald. Je verblijfsplan blijft werken — probeer de verwachting straks opnieuw.', feels:'gevoelstemperatuur', rain:'regen', wind:'wind', uv:'UV', details:'Pas je plan aan het weer aan', forecast:'Verwachting', exactLater:'De nauwkeurige verwachting verschijnt dichter bij aankomst.', conditions:{ clear:'helder', mostlyClear:'meestal zonnig', cloudy:'bewolkt', fog:'mist', drizzle:'motregen', rain:'regen', snow:'sneeuw', storm:'onweer' }, tips:{ tentRain:'Kans op regen — zet de tent goed vast en waterdicht.', heat:'Hoge temperaturen — neem water en een hoed mee.', uv:'Gebruik zonnebrandcrème.', camper:'De rijomstandigheden lijken rustig.', wind:'Zet luifel en lichte spullen vast.' } },
  cs: { title:'Počasí v Krakově', heroLocation:'Krakov · nyní', heroUnavailable:'Předpověď je dočasně nedostupná', live:'Podmínky u kempu', loading:'Kontrolujeme aktuální počasí…', unavailable:'Počasí se nyní nepodařilo načíst. Plán pobytu nadále funguje — zkuste předpověď za chvíli znovu.', feels:'pocitově', rain:'déšť', wind:'vítr', uv:'UV', details:'Přizpůsobit plán počasí', forecast:'Předpověď', exactLater:'Přesná předpověď se zobrazí blíže k příjezdu.', conditions:{ clear:'jasno', mostlyClear:'převážně slunečno', cloudy:'oblačno', fog:'mlha', drizzle:'mrholení', rain:'déšť', snow:'sníh', storm:'bouřka' }, tips:{ tentRain:'Může pršet — dobře zabezpečte stan.', heat:'Vysoké teploty — vezměte vodu a pokrývku hlavy.', uv:'Použijte opalovací krém.', camper:'Podmínky pro příjezd vypadají klidně.', wind:'Zajistěte markýzu a lehké vybavení.' } },
  sk: { title:'Počasie v Krakove', heroLocation:'Krakov · teraz', heroUnavailable:'Predpoveď je dočasne nedostupná', live:'Podmienky pri kempe', loading:'Kontrolujeme aktuálne počasie…', unavailable:'Počasie sa teraz nepodarilo načítať. Plán pobytu naďalej funguje — skúste predpoveď o chvíľu znova.', feels:'pocitovo', rain:'dážď', wind:'vietor', uv:'UV', details:'Prispôsobiť plán počasiu', forecast:'Predpoveď', exactLater:'Presná predpoveď sa zobrazí bližšie k príchodu.', conditions:{ clear:'jasno', mostlyClear:'prevažne slnečno', cloudy:'zamračené', fog:'hmla', drizzle:'mrholenie', rain:'dážď', snow:'sneh', storm:'búrka' }, tips:{ tentRain:'Môže pršať — dobre zabezpečte stan.', heat:'Vysoké teploty — vezmite vodu a pokrývku hlavy.', uv:'Použite opaľovací krém.', camper:'Podmienky na príchod vyzerajú pokojne.', wind:'Zaistite markízu a ľahké vybavenie.' } },
  sv: { title:'Väder i Kraków', heroLocation:'Kraków · nu', heroUnavailable:'Prognosen är tillfälligt otillgänglig', live:'Förhållanden vid campingen', loading:'Hämtar aktuellt väder…', unavailable:'Vädret kunde inte hämtas just nu. Din vistelseplan fungerar fortfarande — kontrollera prognosen igen om en stund.', feels:'känns som', rain:'regn', wind:'vind', uv:'UV', details:'Anpassa planen efter vädret', forecast:'Prognos', exactLater:'Den exakta prognosen visas närmare ankomsten.', conditions:{ clear:'klart', mostlyClear:'mest soligt', cloudy:'molnigt', fog:'dimma', drizzle:'duggregn', rain:'regn', snow:'snö', storm:'åska' }, tips:{ tentRain:'Regn är möjligt — säkra tältet ordentligt.', heat:'Höga temperaturer — ta med vatten och solhatt.', uv:'Använd solskydd.', camper:'Körförhållandena ser lugna ut.', wind:'Säkra markisen och lätt utrustning.' } },
} as const;

export const weatherDrawerCopy = {
  pl: { drawerAria:'Otwórz prognozę pogody dla Krakowa',viewForecast:'Zobacz prognozę',currentWeather:'Aktualna pogoda',hourlyForecast:'Prognoza godzinowa',weekForecast:'Prognoza na 7 dni',humidity:'Wilgotność',today:'Dzisiaj',tomorrow:'Jutro',retry:'Spróbuj ponownie',openPlanner:'Otwórz Planer',askCampy:'Zapytaj CAMPY',close:'Zamknij',updated:'Aktualizacja',recommendationTitle:'Rekomendacja na dziś',campyPrompt:'Pomóż mi dopasować plan pobytu do aktualnej pogody w Krakowie.',hourlyEmpty:'Prognoza godzinowa jest chwilowo niedostępna.',dailyEmpty:'Prognoza kolejnych dni jest chwilowo niedostępna.',recommendations:{ rain:'Możliwy deszcz — sprawdź Plan B i zabierz kurtkę.',heat:'Upał — zaplanuj spokojniejsze tempo i wodę.',clear:'Dobry dzień na Stare Miasto lub wycieczkę do Ojcowa.',wind:'Wiatr — zabezpiecz lekkie wyposażenie na campingu.',neutral:'Dobry dzień na odkrywanie Krakowa.' } },
  en: { drawerAria:'Open the Krakow weather forecast',viewForecast:'View forecast',currentWeather:'Current weather',hourlyForecast:'Hourly forecast',weekForecast:'7-day forecast',humidity:'Humidity',today:'Today',tomorrow:'Tomorrow',retry:'Try again',openPlanner:'Open Planner',askCampy:'Ask CAMPY',close:'Close',updated:'Updated',recommendationTitle:'Today’s recommendation',campyPrompt:'Help me match my stay plan to the current weather in Krakow.',hourlyEmpty:'The hourly forecast is temporarily unavailable.',dailyEmpty:'The multi-day forecast is temporarily unavailable.',recommendations:{ rain:'Rain is possible — check Plan B and take a jacket.',heat:'Hot weather — choose a calmer pace and take water.',clear:'A good day for the Old Town or a trip to Ojców.',wind:'Windy — secure light camping equipment.',neutral:'A good day to explore Krakow.' } },
  de: { drawerAria:'Wettervorhersage für Krakau öffnen',viewForecast:'Vorhersage ansehen',currentWeather:'Aktuelles Wetter',hourlyForecast:'Stündliche Vorhersage',weekForecast:'7-Tage-Vorhersage',humidity:'Luftfeuchtigkeit',today:'Heute',tomorrow:'Morgen',retry:'Erneut versuchen',openPlanner:'Planer öffnen',askCampy:'CAMPY fragen',close:'Schließen',updated:'Aktualisiert',recommendationTitle:'Empfehlung für heute',campyPrompt:'Hilf mir, meinen Aufenthaltsplan an das aktuelle Wetter in Krakau anzupassen.',hourlyEmpty:'Die stündliche Vorhersage ist vorübergehend nicht verfügbar.',dailyEmpty:'Die Mehrtagesvorhersage ist vorübergehend nicht verfügbar.',recommendations:{ rain:'Regen ist möglich — Plan B prüfen und Jacke mitnehmen.',heat:'Hitze — ruhiger planen und Wasser mitnehmen.',clear:'Ein guter Tag für die Altstadt oder einen Ausflug nach Ojców.',wind:'Windig — leichte Campingausrüstung sichern.',neutral:'Ein guter Tag, um Krakau zu entdecken.' } },
  it: { drawerAria:'Apri le previsioni meteo di Cracovia',viewForecast:'Vedi previsioni',currentWeather:'Meteo attuale',hourlyForecast:'Previsioni orarie',weekForecast:'Previsioni a 7 giorni',humidity:'Umidità',today:'Oggi',tomorrow:'Domani',retry:'Riprova',openPlanner:'Apri il Planner',askCampy:'Chiedi a CAMPY',close:'Chiudi',updated:'Aggiornato',recommendationTitle:'Consiglio per oggi',campyPrompt:'Aiutami ad adattare il piano di soggiorno al meteo attuale di Cracovia.',hourlyEmpty:'Le previsioni orarie non sono momentaneamente disponibili.',dailyEmpty:'Le previsioni dei prossimi giorni non sono momentaneamente disponibili.',recommendations:{ rain:'Possibile pioggia — controlla il Piano B e porta una giacca.',heat:'Fa caldo — scegli un ritmo più tranquillo e porta acqua.',clear:'Una buona giornata per il centro storico o una gita a Ojców.',wind:'Vento — fissa l’attrezzatura leggera del camping.',neutral:'Una buona giornata per scoprire Cracovia.' } },
  fr: { drawerAria:'Ouvrir les prévisions météo de Cracovie',viewForecast:'Voir les prévisions',currentWeather:'Météo actuelle',hourlyForecast:'Prévisions horaires',weekForecast:'Prévisions sur 7 jours',humidity:'Humidité',today:'Aujourd’hui',tomorrow:'Demain',retry:'Réessayer',openPlanner:'Ouvrir le Planificateur',askCampy:'Demander à CAMPY',close:'Fermer',updated:'Mis à jour',recommendationTitle:'Conseil du jour',campyPrompt:'Aide-moi à adapter mon programme à la météo actuelle de Cracovie.',hourlyEmpty:'Les prévisions horaires sont momentanément indisponibles.',dailyEmpty:'Les prévisions des prochains jours sont momentanément indisponibles.',recommendations:{ rain:'Pluie possible — consultez le Plan B et prenez une veste.',heat:'Forte chaleur — prévoyez un rythme plus calme et de l’eau.',clear:'Une belle journée pour la vieille ville ou une excursion à Ojców.',wind:'Vent — fixez le matériel léger du camping.',neutral:'Une belle journée pour découvrir Cracovie.' } },
  es: { drawerAria:'Abrir la previsión del tiempo de Cracovia',viewForecast:'Ver previsión',currentWeather:'Tiempo actual',hourlyForecast:'Previsión por horas',weekForecast:'Previsión de 7 días',humidity:'Humedad',today:'Hoy',tomorrow:'Mañana',retry:'Reintentar',openPlanner:'Abrir el Planificador',askCampy:'Preguntar a CAMPY',close:'Cerrar',updated:'Actualizado',recommendationTitle:'Recomendación para hoy',campyPrompt:'Ayúdame a adaptar mi plan de estancia al tiempo actual de Cracovia.',hourlyEmpty:'La previsión por horas no está disponible temporalmente.',dailyEmpty:'La previsión de los próximos días no está disponible temporalmente.',recommendations:{ rain:'Puede llover — revisa el Plan B y lleva chaqueta.',heat:'Hace calor — elige un ritmo más tranquilo y lleva agua.',clear:'Un buen día para el casco antiguo o una excursión a Ojców.',wind:'Viento — asegura el equipo ligero del camping.',neutral:'Un buen día para descubrir Cracovia.' } },
  nl: { drawerAria:'Open de weersverwachting voor Krakau',viewForecast:'Bekijk verwachting',currentWeather:'Actueel weer',hourlyForecast:'Verwachting per uur',weekForecast:'7-daagse verwachting',humidity:'Luchtvochtigheid',today:'Vandaag',tomorrow:'Morgen',retry:'Opnieuw proberen',openPlanner:'Open Planner',askCampy:'Vraag CAMPY',close:'Sluiten',updated:'Bijgewerkt',recommendationTitle:'Advies voor vandaag',campyPrompt:'Help mij mijn verblijfsplan af te stemmen op het actuele weer in Krakau.',hourlyEmpty:'De uurverwachting is tijdelijk niet beschikbaar.',dailyEmpty:'De meerdaagse verwachting is tijdelijk niet beschikbaar.',recommendations:{ rain:'Kans op regen — bekijk Plan B en neem een jas mee.',heat:'Warm weer — kies een rustiger tempo en neem water mee.',clear:'Een goede dag voor de oude stad of een uitstap naar Ojców.',wind:'Wind — zet lichte campingspullen vast.',neutral:'Een goede dag om Krakau te ontdekken.' } },
  cs: { drawerAria:'Otevřít předpověď počasí pro Krakov',viewForecast:'Zobrazit předpověď',currentWeather:'Aktuální počasí',hourlyForecast:'Hodinová předpověď',weekForecast:'Předpověď na 7 dní',humidity:'Vlhkost',today:'Dnes',tomorrow:'Zítra',retry:'Zkusit znovu',openPlanner:'Otevřít Plánovač',askCampy:'Zeptat se CAMPY',close:'Zavřít',updated:'Aktualizováno',recommendationTitle:'Doporučení na dnešek',campyPrompt:'Pomoz mi přizpůsobit plán pobytu aktuálnímu počasí v Krakově.',hourlyEmpty:'Hodinová předpověď je dočasně nedostupná.',dailyEmpty:'Předpověď dalších dní je dočasně nedostupná.',recommendations:{ rain:'Může pršet — zkontrolujte Plán B a vezměte bundu.',heat:'Horko — zvolte klidnější tempo a vezměte vodu.',clear:'Dobrý den pro Staré Město nebo výlet do Ojcova.',wind:'Vítr — zajistěte lehké vybavení kempu.',neutral:'Dobrý den k objevování Krakova.' } },
  sk: { drawerAria:'Otvoriť predpoveď počasia pre Krakov',viewForecast:'Zobraziť predpoveď',currentWeather:'Aktuálne počasie',hourlyForecast:'Hodinová predpoveď',weekForecast:'Predpoveď na 7 dní',humidity:'Vlhkosť',today:'Dnes',tomorrow:'Zajtra',retry:'Skúsiť znova',openPlanner:'Otvoriť Plánovač',askCampy:'Opýtať sa CAMPY',close:'Zavrieť',updated:'Aktualizované',recommendationTitle:'Odporúčanie na dnes',campyPrompt:'Pomôž mi prispôsobiť plán pobytu aktuálnemu počasiu v Krakove.',hourlyEmpty:'Hodinová predpoveď je dočasne nedostupná.',dailyEmpty:'Predpoveď ďalších dní je dočasne nedostupná.',recommendations:{ rain:'Môže pršať — skontrolujte Plán B a vezmite bundu.',heat:'Horúco — zvoľte pokojnejšie tempo a vezmite vodu.',clear:'Dobrý deň na Staré Mesto alebo výlet do Ojcova.',wind:'Vietor — zaistite ľahké vybavenie kempu.',neutral:'Dobrý deň na objavovanie Krakova.' } },
  sv: { drawerAria:'Öppna väderprognosen för Kraków',viewForecast:'Visa prognos',currentWeather:'Aktuellt väder',hourlyForecast:'Timprognos',weekForecast:'7-dygnsprognos',humidity:'Luftfuktighet',today:'I dag',tomorrow:'I morgon',retry:'Försök igen',openPlanner:'Öppna Planeraren',askCampy:'Fråga CAMPY',close:'Stäng',updated:'Uppdaterad',recommendationTitle:'Dagens rekommendation',campyPrompt:'Hjälp mig att anpassa vistelseplanen till det aktuella vädret i Kraków.',hourlyEmpty:'Timprognosen är tillfälligt otillgänglig.',dailyEmpty:'Flerdygnsprognosen är tillfälligt otillgänglig.',recommendations:{ rain:'Regn är möjligt — kontrollera Plan B och ta med jacka.',heat:'Varmt — välj ett lugnare tempo och ta med vatten.',clear:'En bra dag för Gamla stan eller en utflykt till Ojców.',wind:'Blåsigt — säkra lätt campingutrustning.',neutral:'En bra dag att upptäcka Kraków.' } },
} as const;

export const getWeatherCopy = (language = 'pl') => {
  const safeLanguage = weatherLanguages.includes(language as WeatherLanguage) ? language as WeatherLanguage : 'pl';
  return { ...weatherCopy[safeLanguage],...weatherDrawerCopy[safeLanguage] };
};

export const weatherCodeGroup = (code: number) => {
  if (code === 0) return 'clear';
  if ([1, 2].includes(code)) return 'mostlyClear';
  if (code === 3) return 'cloudy';
  if ([45, 48].includes(code)) return 'fog';
  if ([51, 53, 55, 56, 57].includes(code)) return 'drizzle';
  if ([61, 63, 65, 66, 67, 80, 81, 82].includes(code)) return 'rain';
  if ([71, 73, 75, 77, 85, 86].includes(code)) return 'snow';
  if ([95, 96, 99].includes(code)) return 'storm';
  return 'cloudy';
};
