export type WeatherLanguage = 'pl' | 'en' | 'de' | 'it' | 'fr' | 'es' | 'nl' | 'cs' | 'sk' | 'sv';

export const weatherLanguages: WeatherLanguage[] = ['pl', 'en', 'de', 'it', 'fr', 'es', 'nl', 'cs', 'sk', 'sv'];

export const weatherCopy = {
  pl: { title:'Pogoda w Krakowie', live:'Warunki przy campingu', loading:'Sprawdzamy aktualną pogodę…', unavailable:'Pogoda jest chwilowo niedostępna. Sprawdź ponownie za moment.', feels:'odczuwalna', rain:'opady', wind:'wiatr', uv:'UV', details:'Dopasuj plan do pogody', forecast:'Prognoza', exactLater:'Dokładna prognoza pojawi się bliżej przyjazdu.', conditions:{ clear:'bezchmurnie', mostlyClear:'przeważnie słonecznie', cloudy:'pochmurno', fog:'mgła', drizzle:'mżawka', rain:'deszcz', snow:'śnieg', storm:'burza' }, tips:{ tentRain:'Możliwy deszcz — warto zabezpieczyć namiot.', heat:'Wysokie temperatury — zabierz wodę i nakrycie głowy.', uv:'Warto użyć kremu z filtrem.', camper:'Warunki dojazdu wyglądają spokojnie.', wind:'Zabezpiecz markizę i lekkie wyposażenie.' } },
  en: { title:'Weather in Krakow', live:'Conditions by the campsite', loading:'Checking the latest weather…', unavailable:'Weather is temporarily unavailable. Please try again shortly.', feels:'feels like', rain:'rain', wind:'wind', uv:'UV', details:'Match your plan to the weather', forecast:'Forecast', exactLater:'The detailed forecast will appear closer to arrival.', conditions:{ clear:'clear', mostlyClear:'mostly sunny', cloudy:'cloudy', fog:'fog', drizzle:'drizzle', rain:'rain', snow:'snow', storm:'thunderstorm' }, tips:{ tentRain:'Rain is possible — secure your tent.', heat:'High temperatures — take water and a sun hat.', uv:'Use sunscreen.', camper:'Driving conditions look calm.', wind:'Secure the awning and light equipment.' } },
  de: { title:'Wetter in Krakau', live:'Wetter am Campingplatz', loading:'Aktuelles Wetter wird geprüft…', unavailable:'Das Wetter ist vorübergehend nicht verfügbar. Bitte später erneut versuchen.', feels:'gefühlt', rain:'Regen', wind:'Wind', uv:'UV', details:'Plan ans Wetter anpassen', forecast:'Vorhersage', exactLater:'Die genaue Vorhersage erscheint näher an der Anreise.', conditions:{ clear:'klar', mostlyClear:'überwiegend sonnig', cloudy:'bewölkt', fog:'Nebel', drizzle:'Nieselregen', rain:'Regen', snow:'Schnee', storm:'Gewitter' }, tips:{ tentRain:'Regen ist möglich — bitte das Zelt sichern.', heat:'Hohe Temperaturen — Wasser und Kopfbedeckung mitnehmen.', uv:'Sonnenschutz verwenden.', camper:'Die Anreisebedingungen wirken ruhig.', wind:'Markise und leichte Ausrüstung sichern.' } },
  it: { title:'Meteo a Cracovia', live:'Condizioni al camping', loading:'Controllo del meteo aggiornato…', unavailable:'Meteo temporaneamente non disponibile. Riprova tra poco.', feels:'percepita', rain:'pioggia', wind:'vento', uv:'UV', details:'Adatta il piano al meteo', forecast:'Previsioni', exactLater:'Le previsioni precise appariranno più vicino all’arrivo.', conditions:{ clear:'sereno', mostlyClear:'prevalentemente soleggiato', cloudy:'nuvoloso', fog:'nebbia', drizzle:'pioviggine', rain:'pioggia', snow:'neve', storm:'temporale' }, tips:{ tentRain:'Possibile pioggia — proteggi bene la tenda.', heat:'Temperature alte — porta acqua e cappello.', uv:'Usa la crema solare.', camper:'Le condizioni di arrivo sembrano tranquille.', wind:'Fissa tendalino e attrezzatura leggera.' } },
  fr: { title:'Météo à Cracovie', live:'Conditions près du camping', loading:'Vérification de la météo…', unavailable:'La météo est temporairement indisponible. Réessayez dans un instant.', feels:'ressenti', rain:'pluie', wind:'vent', uv:'UV', details:'Adapter le programme à la météo', forecast:'Prévisions', exactLater:'Les prévisions précises apparaîtront à l’approche de l’arrivée.', conditions:{ clear:'ciel dégagé', mostlyClear:'plutôt ensoleillé', cloudy:'nuageux', fog:'brouillard', drizzle:'bruine', rain:'pluie', snow:'neige', storm:'orage' }, tips:{ tentRain:'Pluie possible — protégez bien la tente.', heat:'Températures élevées — prenez de l’eau et un chapeau.', uv:'Utilisez une protection solaire.', camper:'Les conditions d’accès semblent calmes.', wind:'Fixez l’auvent et le matériel léger.' } },
  es: { title:'Tiempo en Cracovia', live:'Condiciones junto al camping', loading:'Consultando el tiempo actual…', unavailable:'El tiempo no está disponible temporalmente. Inténtalo de nuevo en breve.', feels:'sensación', rain:'lluvia', wind:'viento', uv:'UV', details:'Adapta el plan al tiempo', forecast:'Previsión', exactLater:'La previsión detallada aparecerá más cerca de la llegada.', conditions:{ clear:'despejado', mostlyClear:'mayormente soleado', cloudy:'nublado', fog:'niebla', drizzle:'llovizna', rain:'lluvia', snow:'nieve', storm:'tormenta' }, tips:{ tentRain:'Puede llover — protege bien la tienda.', heat:'Temperaturas altas — lleva agua y gorra.', uv:'Usa protector solar.', camper:'Las condiciones de acceso parecen tranquilas.', wind:'Asegura el toldo y el equipo ligero.' } },
  nl: { title:'Weer in Krakau', live:'Omstandigheden bij de camping', loading:'Actueel weer wordt opgehaald…', unavailable:'Het weer is tijdelijk niet beschikbaar. Probeer het zo opnieuw.', feels:'gevoelstemperatuur', rain:'regen', wind:'wind', uv:'UV', details:'Pas je plan aan het weer aan', forecast:'Verwachting', exactLater:'De nauwkeurige verwachting verschijnt dichter bij aankomst.', conditions:{ clear:'helder', mostlyClear:'meestal zonnig', cloudy:'bewolkt', fog:'mist', drizzle:'motregen', rain:'regen', snow:'sneeuw', storm:'onweer' }, tips:{ tentRain:'Kans op regen — zet de tent goed vast en waterdicht.', heat:'Hoge temperaturen — neem water en een hoed mee.', uv:'Gebruik zonnebrandcrème.', camper:'De rijomstandigheden lijken rustig.', wind:'Zet luifel en lichte spullen vast.' } },
  cs: { title:'Počasí v Krakově', live:'Podmínky u kempu', loading:'Kontrolujeme aktuální počasí…', unavailable:'Počasí je dočasně nedostupné. Zkuste to za chvíli znovu.', feels:'pocitově', rain:'déšť', wind:'vítr', uv:'UV', details:'Přizpůsobit plán počasí', forecast:'Předpověď', exactLater:'Přesná předpověď se zobrazí blíže k příjezdu.', conditions:{ clear:'jasno', mostlyClear:'převážně slunečno', cloudy:'oblačno', fog:'mlha', drizzle:'mrholení', rain:'déšť', snow:'sníh', storm:'bouřka' }, tips:{ tentRain:'Může pršet — dobře zabezpečte stan.', heat:'Vysoké teploty — vezměte vodu a pokrývku hlavy.', uv:'Použijte opalovací krém.', camper:'Podmínky pro příjezd vypadají klidně.', wind:'Zajistěte markýzu a lehké vybavení.' } },
  sk: { title:'Počasie v Krakove', live:'Podmienky pri kempe', loading:'Kontrolujeme aktuálne počasie…', unavailable:'Počasie je dočasne nedostupné. Skúste to o chvíľu.', feels:'pocitovo', rain:'dážď', wind:'vietor', uv:'UV', details:'Prispôsobiť plán počasiu', forecast:'Predpoveď', exactLater:'Presná predpoveď sa zobrazí bližšie k príchodu.', conditions:{ clear:'jasno', mostlyClear:'prevažne slnečno', cloudy:'zamračené', fog:'hmla', drizzle:'mrholenie', rain:'dážď', snow:'sneh', storm:'búrka' }, tips:{ tentRain:'Môže pršať — dobre zabezpečte stan.', heat:'Vysoké teploty — vezmite vodu a pokrývku hlavy.', uv:'Použite opaľovací krém.', camper:'Podmienky na príchod vyzerajú pokojne.', wind:'Zaistite markízu a ľahké vybavenie.' } },
  sv: { title:'Väder i Kraków', live:'Förhållanden vid campingen', loading:'Hämtar aktuellt väder…', unavailable:'Vädret är tillfälligt otillgängligt. Försök igen om en stund.', feels:'känns som', rain:'regn', wind:'vind', uv:'UV', details:'Anpassa planen efter vädret', forecast:'Prognos', exactLater:'Den exakta prognosen visas närmare ankomsten.', conditions:{ clear:'klart', mostlyClear:'mest soligt', cloudy:'molnigt', fog:'dimma', drizzle:'duggregn', rain:'regn', snow:'snö', storm:'åska' }, tips:{ tentRain:'Regn är möjligt — säkra tältet ordentligt.', heat:'Höga temperaturer — ta med vatten och solhatt.', uv:'Använd solskydd.', camper:'Körförhållandena ser lugna ut.', wind:'Säkra markisen och lätt utrustning.' } },
} as const;

export const getWeatherCopy = (language = 'pl') =>
  weatherCopy[weatherLanguages.includes(language as WeatherLanguage) ? language as WeatherLanguage : 'pl'];

export const weatherCodeGroup = (code: number) => {
  if (code === 0) return 'clear';
  if ([1, 2].includes(code)) return 'mostlyClear';
  if (code === 3) return 'cloudy';
  if ([45, 48].includes(code)) return 'fog';
  if ([51, 53, 55, 56, 57].includes(code)) return 'drizzle';
  if ([61, 63, 65, 66, 67, 80, 81, 82].includes(code)) return 'rain';
  if ([71, 73, 75, 77, 85, 86].includes(code)) return 'snow';
  if ([95, 96, 99].includes(code)) return 'storm';
  return 'cloudy';
};
