export const summerCampingLanguages = ['pl', 'en', 'de', 'it', 'fr', 'es', 'nl', 'cs', 'sk', 'sv'];

export const summerCampingCopy = {
  pl: {
    title: 'Lipiec i sierpień — miejsca campingowe', badge: 'Spokojnie — zwykle znajdujemy rozwiązanie',
    message: 'W lipcu i sierpniu nie prowadzimy rezerwacji miejsc campingowych z wyprzedzeniem, ale zazwyczaj udaje nam się znaleźć rozwiązanie dla przyjeżdżających gości.',
    noon: 'Najlepsza pora przyjazdu to około godziny 12:00, kiedy zwalniają się miejsca po wyjeżdżających gościach.',
    evening: 'Jeśli przyjedziesz wieczorem, również często znajdziemy rozwiązanie. Przy dużym obłożeniu recepcja może zaproponować bezpieczne miejsce na parkingu na jedną noc, a następnego dnia przenieść pojazd na właściwą część campingu, gdy zwolni się miejsce.',
    disclaimer: 'Dostępność zawsze ocenia recepcja po przyjeździe i nie może być zagwarantowana z wyprzedzeniem.',
    short: 'W lipcu i sierpniu camping działa według kolejności przyjazdu. Najlepiej przyjechać około 12:00; dostępności nie możemy zagwarantować.',
    toast: 'W lipcu i sierpniu nie przyjmujemy zapytań rezerwacyjnych na camping. Wybierz domek albo przyjedź według kolejności przyjazdu.',
    switchToBungalow: 'Zmień na domek', rules: 'Sprawdź zasady przyjazdu', askCampy: 'Zapytaj CAMPY',
    switched: 'Zmieniono typ pobytu na domek. Wybierz domek i możesz wysłać zapytanie.',
    campyPrompt: 'Wyjaśnij spokojnie pełne zasady campingu w lipcu i sierpniu: bez rezerwacji miejsc z wyprzedzeniem, przyjazd najlepiej około 12:00, często możliwe rozwiązanie wieczorem, czasem parking na jedną noc i przeniesienie następnego dnia, bez gwarancji dostępności.',
    summaryLabel: 'Lipiec/sierpień + camping', cta: 'Zobacz możliwości pobytu',
  },
  en: {
    title: 'July and August — camping pitches', badge: 'No stress — we usually find a solution',
    message: 'In July and August we do not reserve camping pitches in advance, but we can usually find a practical solution for arriving guests.',
    noon: 'The best arrival time is around 12:00, when pitches start becoming free after departing guests.',
    evening: 'If you arrive in the evening, we can often still find a solution. When occupancy is high, reception may offer a safe parking place for one night and move the vehicle to the camping area the next day when a pitch becomes free.',
    disclaimer: 'Reception always assesses availability on arrival, and a pitch cannot be guaranteed in advance.',
    short: 'In July and August camping works by arrival order. Around 12:00 is best; availability cannot be guaranteed.',
    toast: 'In July and August we do not accept camping pitch reservation enquiries. Choose a bungalow or arrive in arrival order.',
    switchToBungalow: 'Switch to bungalow', rules: 'Check arrival rules', askCampy: 'Ask CAMPY',
    switched: 'Stay type changed to bungalow. Choose a bungalow and you can send the enquiry.',
    campyPrompt: 'Explain the full July and August camping rule: no advance pitch reservations, arrival ideally around 12:00, an evening solution is often possible, sometimes one-night parking and a move the next day, without guaranteeing availability.',
    summaryLabel: 'July/August + camping', cta: 'See stay options',
  },
  de: {
    title: 'Juli und August — Campingplätze', badge: 'Ganz entspannt — meist finden wir eine Lösung',
    message: 'Im Juli und August reservieren wir Campingplätze nicht im Voraus, können für anreisende Gäste aber meistens eine praktische Lösung finden.',
    noon: 'Die beste Anreisezeit ist gegen 12:00 Uhr, wenn nach der Abreise anderer Gäste Plätze frei werden.',
    evening: 'Auch bei einer Anreise am Abend finden wir häufig eine Lösung. Bei hoher Auslastung kann die Rezeption einen sicheren Parkplatz für eine Nacht anbieten und das Fahrzeug am nächsten Tag auf den Campingbereich umstellen, sobald ein Platz frei wird.',
    disclaimer: 'Die Verfügbarkeit wird immer erst bei der Anreise von der Rezeption beurteilt und kann nicht im Voraus garantiert werden.',
    short: 'Im Juli und August werden Campingplätze nach Ankunftsreihenfolge vergeben. Am besten gegen 12:00 Uhr; keine Verfügbarkeitsgarantie.',
    toast: 'Im Juli und August nehmen wir keine Reservierungsanfragen für Campingplätze an. Wählen Sie einen Bungalow oder reisen Sie nach Ankunftsreihenfolge an.',
    switchToBungalow: 'Zum Bungalow wechseln', rules: 'Anreiseregeln prüfen', askCampy: 'CAMPY fragen',
    switched: 'Der Aufenthaltstyp wurde auf Bungalow geändert. Wählen Sie einen Bungalow und senden Sie die Anfrage.',
    campyPrompt: 'Erkläre die vollständige Campingregel für Juli und August: keine Vorausreservierung, Anreise am besten gegen 12:00 Uhr, abends oft eine Lösung, eventuell Parkplatz für eine Nacht und Umstellen am Folgetag, ohne Verfügbarkeit zu garantieren.',
    summaryLabel: 'Juli/August + Camping', cta: 'Aufenthaltsoptionen ansehen',
  },
  it: {
    title: 'Luglio e agosto — piazzole camping', badge: 'Senza stress — di solito troviamo una soluzione',
    message: 'A luglio e agosto non prenotiamo le piazzole in anticipo, ma di solito riusciamo a trovare una soluzione pratica per gli ospiti in arrivo.',
    noon: 'Il momento migliore per arrivare è verso le 12:00, quando si liberano le piazzole dopo le partenze.',
    evening: 'Anche arrivando la sera spesso troviamo una soluzione. In caso di alta occupazione, la reception può proporre un parcheggio sicuro per una notte e spostare il veicolo nell’area camping il giorno seguente, quando si libera una piazzola.',
    disclaimer: 'La disponibilità viene sempre valutata dalla reception all’arrivo e non può essere garantita in anticipo.',
    short: 'A luglio e agosto le piazzole seguono l’ordine di arrivo. Meglio verso le 12:00; la disponibilità non è garantita.',
    toast: 'A luglio e agosto non accettiamo richieste di prenotazione per piazzole. Scegli un bungalow o arriva in ordine di arrivo.',
    switchToBungalow: 'Passa al bungalow', rules: 'Controlla le regole di arrivo', askCampy: 'Chiedi a CAMPY',
    switched: 'Tipo di soggiorno cambiato in bungalow. Scegli un bungalow e invia la richiesta.',
    campyPrompt: 'Spiega la regola completa di luglio e agosto: niente prenotazioni anticipate delle piazzole, arrivo ideale verso le 12:00, spesso una soluzione anche la sera, talvolta parcheggio per una notte e spostamento il giorno dopo, senza garantire disponibilità.',
    summaryLabel: 'Luglio/agosto + camping', cta: 'Vedi le opzioni di soggiorno',
  },
  fr: {
    title: 'Juillet et août — emplacements de camping', badge: 'En toute sérénité — nous trouvons généralement une solution',
    message: 'En juillet et août, nous ne réservons pas les emplacements à l’avance, mais nous trouvons généralement une solution pratique pour les clients qui arrivent.',
    noon: 'Le meilleur moment pour arriver est vers 12h00, lorsque des emplacements se libèrent après les départs.',
    evening: 'Même le soir, nous trouvons souvent une solution. En cas de forte occupation, la réception peut proposer un parking sûr pour une nuit, puis déplacer le véhicule vers la zone de camping le lendemain lorsqu’un emplacement se libère.',
    disclaimer: 'La disponibilité est toujours évaluée par la réception à l’arrivée et ne peut pas être garantie à l’avance.',
    short: 'En juillet et août, les emplacements sont attribués par ordre d’arrivée. Venez idéalement vers 12h00 ; disponibilité non garantie.',
    toast: 'En juillet et août, nous ne prenons pas de demandes de réservation d’emplacement. Choisissez un bungalow ou venez par ordre d’arrivée.',
    switchToBungalow: 'Passer au bungalow', rules: 'Voir les règles d’arrivée', askCampy: 'Demander à CAMPY',
    switched: 'Le séjour a été changé en bungalow. Choisissez un bungalow puis envoyez la demande.',
    campyPrompt: 'Explique la règle complète de juillet et août : pas de réservation anticipée des emplacements, arrivée idéale vers 12h00, solution souvent possible le soir, parfois parking une nuit puis déplacement le lendemain, sans garantir la disponibilité.',
    summaryLabel: 'Juillet/août + camping', cta: 'Voir les options de séjour',
  },
  es: {
    title: 'Julio y agosto — parcelas de camping', badge: 'Con tranquilidad — normalmente encontramos una solución',
    message: 'En julio y agosto no reservamos parcelas con antelación, pero normalmente podemos encontrar una solución práctica para quienes llegan.',
    noon: 'La mejor hora de llegada es alrededor de las 12:00, cuando quedan libres parcelas tras las salidas.',
    evening: 'Si llegas por la tarde o noche, a menudo también encontramos una solución. Con alta ocupación, recepción puede ofrecer un aparcamiento seguro por una noche y mover el vehículo al camping al día siguiente cuando quede una parcela libre.',
    disclaimer: 'Recepción evalúa siempre la disponibilidad al llegar y no puede garantizarse por adelantado.',
    short: 'En julio y agosto las parcelas se asignan por orden de llegada. Mejor sobre las 12:00; disponibilidad no garantizada.',
    toast: 'En julio y agosto no aceptamos consultas de reserva de parcelas. Elige bungalow o llega por orden de llegada.',
    switchToBungalow: 'Cambiar a bungalow', rules: 'Ver reglas de llegada', askCampy: 'Preguntar a CAMPY',
    switched: 'El tipo de estancia se cambió a bungalow. Elige uno y envía la consulta.',
    campyPrompt: 'Explica la regla completa de julio y agosto: sin reservas anticipadas de parcelas, llegada ideal sobre las 12:00, solución frecuente por la noche, a veces aparcamiento una noche y traslado al día siguiente, sin garantizar disponibilidad.',
    summaryLabel: 'Julio/agosto + camping', cta: 'Ver opciones de estancia',
  },
  nl: {
    title: 'Juli en augustus — kampeerplaatsen', badge: 'Geen zorgen — meestal vinden we een oplossing',
    message: 'In juli en augustus reserveren we kampeerplaatsen niet vooraf, maar voor aankomende gasten vinden we meestal een praktische oplossing.',
    noon: 'De beste aankomsttijd is rond 12.00 uur, wanneer plaatsen vrijkomen na vertrekkende gasten.',
    evening: 'Ook bij aankomst in de avond vinden we vaak een oplossing. Bij hoge bezetting kan de receptie een veilige parkeerplek voor één nacht aanbieden en het voertuig de volgende dag naar het campinggedeelte verplaatsen zodra er plaats vrijkomt.',
    disclaimer: 'De receptie beoordeelt de beschikbaarheid altijd bij aankomst; een plaats kan vooraf niet worden gegarandeerd.',
    short: 'In juli en augustus geldt de volgorde van aankomst. Kom liefst rond 12.00 uur; beschikbaarheid is niet gegarandeerd.',
    toast: 'In juli en augustus nemen we geen reserveringsaanvragen voor kampeerplaatsen aan. Kies een bungalow of kom op volgorde van aankomst.',
    switchToBungalow: 'Wijzig naar bungalow', rules: 'Bekijk aankomstregels', askCampy: 'Vraag CAMPY',
    switched: 'Het verblijfstype is gewijzigd naar bungalow. Kies een bungalow en verstuur de aanvraag.',
    campyPrompt: 'Leg de volledige regel voor juli en augustus uit: geen vooraf gereserveerde plaatsen, aankomst liefst rond 12.00 uur, ’s avonds vaak een oplossing, soms één nacht parkeren en de volgende dag verplaatsen, zonder beschikbaarheid te garanderen.',
    summaryLabel: 'Juli/augustus + camping', cta: 'Bekijk verblijfsopties',
  },
  cs: {
    title: 'Červenec a srpen — místa v kempu', badge: 'Bez obav — obvykle najdeme řešení',
    message: 'V červenci a srpnu nerezervujeme místa v kempu předem, ale pro přijíždějící hosty obvykle dokážeme najít praktické řešení.',
    noon: 'Nejlepší čas příjezdu je kolem 12:00, kdy se uvolňují místa po odjíždějících hostech.',
    evening: 'Také při večerním příjezdu často najdeme řešení. Při vysoké obsazenosti může recepce nabídnout bezpečné parkování na jednu noc a následující den vozidlo přesunout do kempu, jakmile se uvolní místo.',
    disclaimer: 'Dostupnost vždy posuzuje recepce až při příjezdu a nelze ji předem zaručit.',
    short: 'V červenci a srpnu platí pořadí příjezdu. Nejlépe kolem 12:00; dostupnost nelze zaručit.',
    toast: 'V červenci a srpnu nepřijímáme rezervační dotazy na místa v kempu. Vyberte bungalov nebo přijeďte podle pořadí.',
    switchToBungalow: 'Změnit na bungalov', rules: 'Zkontrolovat pravidla příjezdu', askCampy: 'Zeptat se CAMPY',
    switched: 'Typ pobytu byl změněn na bungalov. Vyberte bungalov a odešlete dotaz.',
    campyPrompt: 'Vysvětli úplné pravidlo pro červenec a srpen: bez rezervací míst předem, příjezd nejlépe kolem 12:00, večer často řešení, někdy parkování na noc a přesun další den, bez záruky dostupnosti.',
    summaryLabel: 'Červenec/srpen + camping', cta: 'Zobrazit možnosti pobytu',
  },
  sk: {
    title: 'Júl a august — miesta v kempe', badge: 'Bez obáv — zvyčajne nájdeme riešenie',
    message: 'V júli a auguste nerezervujeme miesta v kempe vopred, ale pre prichádzajúcich hostí zvyčajne dokážeme nájsť praktické riešenie.',
    noon: 'Najlepší čas príchodu je okolo 12:00, keď sa uvoľňujú miesta po odchádzajúcich hosťoch.',
    evening: 'Aj pri večernom príchode často nájdeme riešenie. Pri vysokej obsadenosti môže recepcia ponúknuť bezpečné parkovanie na jednu noc a na ďalší deň vozidlo presunúť do kempu, keď sa uvoľní miesto.',
    disclaimer: 'Dostupnosť vždy posudzuje recepcia až pri príchode a nemožno ju vopred zaručiť.',
    short: 'V júli a auguste platí poradie príchodu. Najlepšie okolo 12:00; dostupnosť nemožno zaručiť.',
    toast: 'V júli a auguste neprijímame rezervačné dopyty na miesta v kempe. Vyberte bungalov alebo príďte podľa poradia.',
    switchToBungalow: 'Zmeniť na bungalov', rules: 'Skontrolovať pravidlá príchodu', askCampy: 'Opýtať sa CAMPY',
    switched: 'Typ pobytu bol zmenený na bungalov. Vyberte bungalov a odošlite dopyt.',
    campyPrompt: 'Vysvetli úplné pravidlo pre júl a august: bez rezervácie miest vopred, príchod najlepšie okolo 12:00, večer často riešenie, niekedy parkovanie na noc a presun ďalší deň, bez záruky dostupnosti.',
    summaryLabel: 'Júl/august + camping', cta: 'Zobraziť možnosti pobytu',
  },
  sv: {
    title: 'Juli och augusti — campingplatser', badge: 'Ingen stress — oftast hittar vi en lösning',
    message: 'I juli och augusti förhandsbokar vi inte campingplatser, men vi kan oftast hitta en praktisk lösning för ankommande gäster.',
    noon: 'Bästa ankomsttid är omkring 12.00, när platser börjar bli lediga efter avresande gäster.',
    evening: 'Även vid ankomst på kvällen hittar vi ofta en lösning. Vid hög beläggning kan receptionen erbjuda en säker parkeringsplats för en natt och flytta fordonet till campingområdet nästa dag när en plats blir ledig.',
    disclaimer: 'Receptionen bedömer alltid tillgängligheten vid ankomst och en plats kan inte garanteras i förväg.',
    short: 'I juli och augusti gäller ankomstordning. Kom helst runt 12.00; tillgänglighet kan inte garanteras.',
    toast: 'I juli och augusti tar vi inte emot bokningsförfrågningar för campingplatser. Välj bungalow eller kom i ankomstordning.',
    switchToBungalow: 'Byt till bungalow', rules: 'Kontrollera ankomstregler', askCampy: 'Fråga CAMPY',
    switched: 'Vistelsen ändrades till bungalow. Välj en bungalow och skicka förfrågan.',
    campyPrompt: 'Förklara hela regeln för juli och augusti: inga förhandsbokade platser, ankomst helst runt 12.00, ofta en lösning på kvällen, ibland parkering en natt och flytt nästa dag, utan att garantera tillgänglighet.',
    summaryLabel: 'Juli/augusti + camping', cta: 'Se boendealternativ',
  },
};

export const getSummerCampingCopy = (language = 'pl') =>
  summerCampingCopy[summerCampingLanguages.includes(String(language).toLowerCase()) ? String(language).toLowerCase() : 'pl'];

export const summerCampingFullText = (language = 'pl') => {
  const copy = getSummerCampingCopy(language);
  return `${copy.message}\n\n${copy.noon}\n\n${copy.evening}\n\n${copy.disclaimer}`;
};
